/**
 * Data loader for Airport Code Resolver.
 *
 * Loads processed JSON datasets from disk into memory.
 * Datasets are generated by scripts/download-airport-data.ts.
 */

import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { ProcessedAirport, MetroArea, DecommissionedAirport } from './types.js';

export interface AirportDataset {
  airports: ProcessedAirport[];
  metroAreas: MetroArea[];
  decommissioned: DecommissionedAirport[];
  loadedAt: Date;
  /**
   * Which optional datasets were present on disk at load time. `airports.json`
   * is required (load throws if missing); these two are optional and drive a
   * `degraded` health status when absent.
   */
  optionalDatasets: {
    metroAreas: boolean;
    decommissioned: boolean;
  };
}

const DATA_DIR = join(process.cwd(), 'data', 'reference');

async function loadJsonFile<T>(filepath: string): Promise<T> {
  const raw = await readFile(filepath, 'utf-8');
  return JSON.parse(raw) as T;
}

/**
 * Load all airport datasets from disk.
 * Throws if airports.json is missing (required).
 * Metro areas and decommissioned data are optional — returns empty arrays if missing.
 */
export async function loadAirportData(dataDir?: string): Promise<AirportDataset> {
  const dir = dataDir ?? DATA_DIR;
  const airportsPath = join(dir, 'airports.json');
  const metroPath = join(dir, 'metro-areas.json');
  const decommissionedPath = join(dir, 'decommissioned.json');

  if (!existsSync(airportsPath)) {
    throw new Error(
      `Airport data not found at ${airportsPath}. Run "pnpm run data:download" first.`,
    );
  }

  const airports = await loadJsonFile<ProcessedAirport[]>(airportsPath);

  const hasMetro = existsSync(metroPath);
  const hasDecommissioned = existsSync(decommissionedPath);

  const metroAreas = hasMetro ? await loadJsonFile<MetroArea[]>(metroPath) : [];

  const decommissioned = hasDecommissioned
    ? await loadJsonFile<DecommissionedAirport[]>(decommissionedPath)
    : [];

  return {
    airports,
    metroAreas,
    decommissioned,
    loadedAt: new Date(),
    optionalDatasets: {
      metroAreas: hasMetro,
      decommissioned: hasDecommissioned,
    },
  };
}
