#!/usr/bin/env tsx
/**
 * Render `docs/agent-map.html` from an AgentGraph.
 *
 * Apple-style product presentation of the Otaip agent system for Telivity:
 * light fog background, Montserrat, teal/navy brand tokens from telivity.app,
 * dramatic hero, cinematic journey sequence, bento stage grid, and workflow
 * strips. Generated by `pnpm gen:manifest` / `pnpm gen:agent-map`.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AgentGraph, AgentGraphNode } from './agent-graph.js';

const GRAPH_PATH = 'agents.graph.json';
const MAP_HTML_PATH = 'docs/agent-map.html';

const STAGE_ORDER = [
  'reference',
  'search',
  'pricing',
  'booking',
  'ticketing',
  'exchange',
  'settlement',
  'reconciliation',
  'tmc',
  'platform',
  'core',
  'lodging',
] as const;

const STAGE_DISPLAY: Readonly<Record<string, string>> = {
  reference: 'Reference',
  search: 'Search',
  pricing: 'Pricing',
  booking: 'Booking',
  ticketing: 'Ticketing',
  exchange: 'Exchange',
  settlement: 'Settlement',
  reconciliation: 'Reconciliation',
  tmc: 'TMC',
  platform: 'Platform',
  core: 'Core',
  lodging: 'Lodging',
};

/** Cinematic journey acts — each maps to a real stage for its agent count. */
const JOURNEY: ReadonlyArray<{ word: string; stage: string }> = [
  { word: 'Search', stage: 'search' },
  { word: 'Price', stage: 'pricing' },
  { word: 'Book', stage: 'booking' },
  { word: 'Ticket', stage: 'ticketing' },
  { word: 'Exchange', stage: 'exchange' },
  { word: 'Settle', stage: 'settlement' },
];

/** Bento grid column spans per stage (6-column grid). */
const BENTO_SPAN: Readonly<Record<string, string>> = {
  search: 'span-3',
  pricing: 'span-3',
  booking: 'span-4',
  ticketing: 'span-2',
  exchange: 'span-2',
  settlement: 'span-2',
  reconciliation: 'span-2',
  reference: 'span-2',
  tmc: 'span-2',
  core: 'span-2',
  lodging: 'span-3',
  platform: 'span-3',
};

function repoRoot(): string {
  let cur = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(cur, 'pnpm-workspace.yaml'))) return cur;
    const parent = dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return resolve(dirname(fileURLToPath(import.meta.url)), '..');
}

function compareAgentIds(a: string, b: string): number {
  const [aMajor = 0, aMinor = 0] = a.split('.').map(Number);
  const [bMajor = 0, bMinor = 0] = b.split('.').map(Number);
  return aMajor - bMajor || aMinor - bMinor || a.localeCompare(b);
}

function stageSortKey(stage: string): number {
  const idx = (STAGE_ORDER as readonly string[]).indexOf(stage);
  return idx === -1 ? 1000 : idx;
}

function stageDisplay(stage: string): string {
  return STAGE_DISPLAY[stage] ?? stage.charAt(0).toUpperCase() + stage.slice(1);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function groupByStage(nodes: readonly AgentGraphNode[]): Array<[string, AgentGraphNode[]]> {
  const map = new Map<string, AgentGraphNode[]>();
  for (const n of nodes) {
    const list = map.get(n.stage) ?? [];
    list.push(n);
    map.set(n.stage, list);
  }
  for (const list of map.values()) {
    list.sort((a, b) => compareAgentIds(a.id, b.id));
  }
  return [...map.entries()].sort(([a], [b]) => stageSortKey(a) - stageSortKey(b) || a.localeCompare(b));
}

interface WorkflowSequence {
  readonly label: string;
  readonly ids: readonly string[];
}

/** Reconstruct the ordered agent path of each workflow from its edges. */
function workflowSequences(graph: AgentGraph): WorkflowSequence[] {
  const byLabel = new Map<string, Array<{ source: string; target: string }>>();
  for (const e of graph.edges) {
    if (e.kind !== 'workflow') continue;
    const list = byLabel.get(e.label) ?? [];
    list.push({ source: e.source, target: e.target });
    byLabel.set(e.label, list);
  }
  const out: WorkflowSequence[] = [];
  for (const [label, edges] of byLabel) {
    const targets = new Set(edges.map((e) => e.target));
    const start = edges.map((e) => e.source).find((s) => !targets.has(s));
    const next = new Map(edges.map((e) => [e.source, e.target]));
    const ids: string[] = [];
    let cur: string | undefined = start ?? edges[0]?.source;
    while (cur !== undefined && ids.length <= edges.length) {
      ids.push(cur);
      cur = next.get(cur);
    }
    for (const e of edges) {
      if (!ids.includes(e.source)) ids.push(e.source);
      if (!ids.includes(e.target)) ids.push(e.target);
    }
    out.push({ label, ids });
  }
  out.sort((a, b) =>
    a.label === 'full_booking' ? -1 : b.label === 'full_booking' ? 1 : a.label.localeCompare(b.label),
  );
  return out;
}

export function renderAgentMapHtml(graph: AgentGraph): string {
  const stages = groupByStage(graph.nodes);
  const stageMap = new Map(stages);
  const nodeById = new Map(graph.nodes.map((n) => [n.id, n]));
  const workflows = workflowSequences(graph);

  const journeyHtml = JOURNEY.filter((j) => stageMap.has(j.stage))
    .map((j, i) => {
      const count = stageMap.get(j.stage)?.length ?? 0;
      return `          <button type="button" class="jstep" data-stage-target="${escapeHtml(j.stage)}" data-reveal style="--i:${i + 1}">
            <span class="num">${String(i + 1).padStart(2, '0')}</span>
            <span class="word">${escapeHtml(j.word)}</span>
            <span class="meta">${count} agent${count === 1 ? '' : 's'}</span>
          </button>`;
    })
    .join('\n');

  const tilesHtml = stages
    .map(([stage, agents], i) => {
      const span = BENTO_SPAN[stage] ?? 'span-3';
      const preview =
        agents
          .slice(0, 2)
          .map((a) => a.name)
          .join(' · ') + (agents.length > 2 ? ` · +${agents.length - 2}` : '');
      const rows = agents
        .map((a) => {
          const stub = a.contract_status === 'stub';
          return `              <li><button type="button" class="agent-row" data-agent="${escapeHtml(a.id)}">
                <span class="a-dot${stub ? ' stub' : ''}" aria-hidden="true"></span>
                <span class="a-id">${escapeHtml(a.id)}</span>
                <span class="a-name">${escapeHtml(a.name)}</span>
                <span class="a-status">${a.contract_status}</span>
              </button></li>`;
        })
        .join('\n');
      return `        <section class="tile ${span}" id="tile-${escapeHtml(stage)}" data-stage="${escapeHtml(stage)}" data-reveal style="--i:${i % 3}">
          <button type="button" class="tile-head" aria-expanded="false">
            <span class="tile-top">
              <span class="tile-stage">${escapeHtml(stageDisplay(stage))}</span>
              <span class="tile-chevron" aria-hidden="true"></span>
            </span>
            <span class="tile-count">${agents.length}<em>agent${agents.length === 1 ? '' : 's'}</em></span>
            <span class="tile-preview">${escapeHtml(preview)}</span>
            <span class="tile-match" aria-live="polite"></span>
            <span class="tile-wm" aria-hidden="true">${String(i + 1).padStart(2, '0')}</span>
          </button>
          <div class="tile-body">
            <ul class="agent-list">
${rows}
            </ul>
          </div>
        </section>`;
    })
    .join('\n');

  const wfRowsHtml = workflows
    .map((wf, i) => {
      const chips: string[] = [];
      wf.ids.forEach((id, idx) => {
        const n = nodeById.get(id);
        if (!n) return;
        if (idx > 0) chips.push('<span class="wf-link" aria-hidden="true"></span>');
        chips.push(
          `<button type="button" class="wf-chip" data-agent="${escapeHtml(id)}"><span class="wf-id">${escapeHtml(id)}</span> ${escapeHtml(n.name)}</button>`,
        );
      });
      const featured = wf.label === 'full_booking';
      return `        <div class="wf-row${featured ? ' featured' : ''}" data-wf="${escapeHtml(wf.label)}" data-reveal style="--i:${i}">
          <div class="wf-meta">
            <span class="wf-name">${escapeHtml(wf.label)}</span>
            <span class="wf-count">${wf.ids.length} agents · Orchestrator pipeline</span>
          </div>
          <div class="wf-path">
            ${chips.join('\n            ')}
          </div>
        </div>`;
    })
    .join('\n');

  const payload = JSON.stringify(graph);
  const stageNamesJson = JSON.stringify(STAGE_DISPLAY);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Telivity · Otaip Agent System</title>
  <meta name="description" content="Telivity Otaip agent system — typed travel AI agents from search to settlement." />
  <link rel="icon" href="assets/telivity/favicon.ico" sizes="any" />
  <link rel="icon" href="assets/telivity/favicon.svg" type="image/svg+xml" />
  <meta property="og:image" content="assets/telivity/og-image.png" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap" rel="stylesheet" />
  <noscript><style>[data-reveal] { opacity: 1 !important; transform: none !important; }</style></noscript>
  <style>
    :root {
      /* Telivity brand — from telivity.app */
      --teal: #06bdb4;
      --teal-dark: #00a692;
      --teal-light: #2cd1b9;
      --navy: #23273d;
      --slate: #444863;
      --mid: #bbbbc4;
      --yellow: #eec517;
      --orange: #f2641b;
      --purple: #a890ff;
      --fog: #f0f0f6;
      --ink-1: var(--navy);
      --ink-2: var(--slate);
      --ink-3: #7a7e96;
      --ink-4: #9aa0b4;
      --hairline: rgba(35, 39, 61, 0.09);
      --hairline-strong: rgba(35, 39, 61, 0.16);
      --hairline-mid: rgba(187, 187, 196, 0.38);
      --tile: #ffffff;
      --shadow-soft:
        0 1px 2px rgba(35, 39, 61, 0.05),
        0 10px 28px -10px rgba(35, 39, 61, 0.1),
        0 32px 64px -24px rgba(35, 39, 61, 0.12);
      --shadow-lift:
        0 2px 6px rgba(35, 39, 61, 0.06),
        0 18px 40px -14px rgba(35, 39, 61, 0.16),
        0 48px 96px -32px rgba(35, 39, 61, 0.18);
      --font: "Montserrat", system-ui, sans-serif;
      --mono: ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace;
      --spring: cubic-bezier(0.34, 1.3, 0.64, 1);
      --ease-out: cubic-bezier(0.22, 1, 0.36, 1);
    }
    * { box-sizing: border-box; }
    html { scroll-behavior: smooth; }
    html, body { margin: 0; min-height: 100%; }
    body {
      font-family: var(--font);
      color: var(--ink-1);
      background:
        radial-gradient(1200px 700px at 85% -10%, rgba(6, 189, 180, 0.06), transparent 60%),
        radial-gradient(900px 600px at -10% 30%, rgba(44, 209, 185, 0.05), transparent 55%),
        var(--fog);
      -webkit-font-smoothing: antialiased;
      text-rendering: optimizeLegibility;
    }
    body::after {
      content: "";
      position: fixed;
      inset: 0;
      z-index: 200;
      pointer-events: none;
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='180' height='180' filter='url(%23n)'/%3E%3C/svg%3E");
      opacity: 0.045;
      mix-blend-mode: multiply;
    }
    ::selection { background: rgba(6, 189, 180, 0.25); }
    a { color: var(--teal-dark); }
    :focus-visible { outline: 2px solid var(--teal); outline-offset: 2px; border-radius: 4px; }

    .shell { max-width: 74rem; margin: 0 auto; padding: 0 1.5rem; }

    /* ---------- Nav ---------- */
    .nav {
      position: sticky;
      top: 0;
      z-index: 100;
      backdrop-filter: blur(16px);
      -webkit-backdrop-filter: blur(16px);
      background: rgba(240, 240, 246, 0.65);
      transition: background 0.3s ease, box-shadow 0.3s ease;
    }
    .nav.scrolled {
      background: rgba(240, 240, 246, 0.88);
      box-shadow: 0 1px 0 var(--hairline);
    }
    .nav-inner {
      max-width: 74rem;
      margin: 0 auto;
      padding: 0.8rem 1.5rem;
      display: flex;
      align-items: center;
      gap: 2rem;
    }
    .brand {
      display: inline-flex;
      align-items: center;
      gap: 0.55rem;
      text-decoration: none;
      color: var(--navy);
    }
    .brand img { width: 26px; height: 26px; display: block; }
    .brand-name { font-weight: 700; font-size: 1.12rem; letter-spacing: -0.02em; }
    .nav-links { margin-left: auto; display: flex; gap: 1.7rem; align-items: center; }
    .nav-links a {
      color: var(--slate);
      text-decoration: none;
      font-size: 0.82rem;
      font-weight: 500;
      transition: color 0.15s ease;
    }
    .nav-links a:hover { color: var(--teal-dark); }
    .nav-links a.ext { color: var(--ink-4); }
    @media (max-width: 640px) {
      .nav-links { gap: 1rem; }
      .nav-links a.ext { display: none; }
    }

    /* ---------- Hero ---------- */
    .hero {
      position: relative;
      min-height: calc(100svh - 3.6rem);
      display: grid;
      place-items: center;
      overflow: hidden;
      text-align: center;
      padding: 4rem 1.5rem 10rem;
    }
    .hero-inner { position: relative; z-index: 2; max-width: 62rem; }
    .hero-brand {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 1.05rem;
      margin-bottom: 1.5rem;
    }
    .hero-mark { width: 76px; height: 76px; display: block; }
    .hero-wordmark {
      font-weight: 700;
      font-size: clamp(1.9rem, 3.2vw, 2.5rem);
      letter-spacing: -0.03em;
      line-height: 1;
      color: var(--navy);
    }
    .eyebrow {
      margin: 0 0 1.4rem;
      font-size: 0.72rem;
      font-weight: 600;
      letter-spacing: 0.26em;
      text-transform: uppercase;
      color: var(--teal-dark);
    }
    h1 {
      margin: 0;
      font-weight: 700;
      font-size: clamp(3.5rem, 8vw, 6.5rem);
      letter-spacing: -0.045em;
      line-height: 1.0;
      color: var(--navy);
    }
    h1 .grad {
      background: linear-gradient(100deg, var(--teal-dark) 0%, var(--teal) 45%, var(--teal-light) 100%);
      -webkit-background-clip: text;
      background-clip: text;
      color: transparent;
    }
    .lede {
      margin: 1.6rem auto 0;
      max-width: 40rem;
      font-size: clamp(1.05rem, 1.7vw, 1.3rem);
      font-weight: 300;
      line-height: 1.6;
      color: var(--ink-2);
    }
    .cta {
      margin-top: 2.75rem;
      display: flex;
      gap: 0.9rem;
      justify-content: center;
      align-items: center;
      flex-wrap: wrap;
    }
    .btn {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      border-radius: 13px;
      font-weight: 600;
      font-size: 1rem;
      text-decoration: none;
      padding: 0.95rem 1.9rem;
      transition: transform 0.3s var(--spring), box-shadow 0.3s ease, background 0.2s ease, color 0.2s ease, border-color 0.2s ease;
    }
    .btn-primary {
      background: var(--teal);
      color: #fff;
      box-shadow: 0 2px 6px rgba(0, 166, 146, 0.35), 0 18px 36px -14px rgba(6, 189, 180, 0.55);
    }
    .btn-primary:hover {
      background: var(--teal-dark);
      transform: translateY(-2px);
      box-shadow: 0 4px 10px rgba(0, 166, 146, 0.4), 0 24px 44px -14px rgba(0, 166, 146, 0.55);
    }
    .btn-ghost {
      color: var(--navy);
      border: 1px solid var(--hairline-strong);
      background: rgba(255, 255, 255, 0.55);
      padding: 0.95rem 1.6rem;
    }
    .btn-ghost:hover { border-color: var(--teal); color: var(--teal-dark); background: #fff; }
    .btn-ghost .arr { display: inline-block; transition: transform 0.3s var(--spring); }
    .btn-ghost:hover .arr { transform: translateX(4px); }

    .hero-stage { position: absolute; inset: 0; z-index: 1; pointer-events: none; }
    .hero-watermark {
      position: absolute;
      left: 50%;
      top: 44%;
      transform: translate(-50%, -50%);
      font-weight: 700;
      font-size: 26vw;
      letter-spacing: -0.05em;
      line-height: 1;
      color: rgba(35, 39, 61, 0.033);
      white-space: nowrap;
      user-select: none;
    }
    .orb { position: absolute; border-radius: 50%; filter: blur(70px); }
    .orb-a {
      width: 52vw; height: 52vw; left: -14vw; top: -16vw;
      background: radial-gradient(circle, rgba(6, 189, 180, 0.24), transparent 65%);
      animation: drift 24s ease-in-out infinite alternate;
    }
    .orb-b {
      width: 38vw; height: 38vw; right: -10vw; top: 2vh;
      background: radial-gradient(circle, rgba(168, 144, 255, 0.12), transparent 65%);
      animation: drift 28s ease-in-out infinite alternate-reverse;
    }
    .orb-c {
      width: 34vw; height: 34vw; left: 30vw; bottom: -14vw;
      background: radial-gradient(circle, rgba(238, 197, 23, 0.13), transparent 65%);
      animation: drift 32s ease-in-out infinite alternate;
    }
    @keyframes drift {
      from { transform: translate3d(0, 0, 0) scale(1); }
      to { transform: translate3d(3vw, -2.5vh, 0) scale(1.07); }
    }
    .horizon {
      position: absolute;
      left: 50%;
      bottom: -46%;
      width: 160%;
      aspect-ratio: 2.7 / 1;
      transform: translateX(-50%);
      border-radius: 50%;
      background: radial-gradient(50% 50% at 50% 50%, rgba(6, 189, 180, 0.3), rgba(44, 209, 185, 0.13) 45%, rgba(240, 240, 246, 0) 72%);
    }
    .horizon::before {
      content: "";
      position: absolute;
      inset: -1.5%;
      border-radius: 50%;
      border-top: 1px solid rgba(6, 189, 180, 0.35);
    }

    /* ---------- Sections ---------- */
    .section { padding: 8rem 0; scroll-margin-top: 3.5rem; }
    .section.alt {
      background: #fff;
      border-top: 1px solid var(--hairline);
      border-bottom: 1px solid var(--hairline);
    }
    .s-head { max-width: 46rem; margin-bottom: 4.25rem; }
    .s-head h2 {
      margin: 0;
      font-size: clamp(2.6rem, 5.4vw, 4.2rem);
      font-weight: 700;
      letter-spacing: -0.04em;
      line-height: 1.02;
      color: var(--navy);
    }
    .s-head .sub {
      margin: 1.25rem 0 0;
      font-size: 1.1rem;
      font-weight: 300;
      line-height: 1.55;
      color: var(--ink-3);
    }

    [data-reveal] {
      opacity: 0;
      transform: translateY(26px);
      transition: opacity 0.7s ease, transform 0.85s var(--spring);
      transition-delay: calc(var(--i, 0) * 70ms);
    }
    [data-reveal].in { opacity: 1; transform: none; }

    /* ---------- Journey ---------- */
    .journey-track {
      position: relative;
      display: grid;
      grid-template-columns: repeat(6, 1fr);
      gap: 2.25rem;
    }
    .journey-track::before {
      content: "";
      position: absolute;
      top: 5px;
      left: 1%;
      right: 1%;
      height: 1px;
      background: linear-gradient(90deg, transparent, rgba(35, 39, 61, 0.2) 10%, rgba(35, 39, 61, 0.2) 90%, transparent);
    }
    .jstep {
      position: relative;
      padding: 2.7rem 0 0;
      background: none;
      border: 0;
      font: inherit;
      text-align: left;
      cursor: pointer;
      color: inherit;
    }
    .jstep::before {
      content: "";
      position: absolute;
      top: 0;
      left: 0;
      width: 11px;
      height: 11px;
      border-radius: 50%;
      background: #fff;
      border: 2px solid var(--teal);
      transition: background 0.25s ease, box-shadow 0.25s ease, transform 0.3s var(--spring);
    }
    .jstep:hover::before,
    .jstep:focus-visible::before {
      background: var(--teal);
      box-shadow: 0 0 0 7px rgba(6, 189, 180, 0.16);
      transform: scale(1.15);
    }
    .jstep .num {
      font-weight: 300;
      font-size: 1.05rem;
      letter-spacing: 0.2em;
      color: var(--teal-dark);
    }
    .jstep .word {
      display: block;
      margin: 0.6rem 0 0.55rem;
      font-size: clamp(2.1rem, 3.9vw, 3.4rem);
      font-weight: 700;
      letter-spacing: -0.04em;
      line-height: 1.0;
      color: var(--navy);
      transition: color 0.2s ease;
    }
    .jstep:hover .word { color: var(--teal-dark); }
    .jstep .meta {
      font-size: 0.74rem;
      font-weight: 400;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--ink-4);
    }
    @media (max-width: 860px) {
      .journey-track {
        grid-template-columns: none;
        grid-auto-flow: column;
        grid-auto-columns: 58%;
        overflow-x: auto;
        scroll-snap-type: x mandatory;
        padding-bottom: 1rem;
        margin: 0 -1.5rem;
        padding-left: 1.5rem;
        padding-right: 1.5rem;
      }
      .journey-track::before { left: 1.5rem; right: 1.5rem; }
      .jstep { scroll-snap-align: start; }
    }

    /* ---------- Controls (below the fold) ---------- */
    .controls {
      display: flex;
      flex-wrap: wrap;
      gap: 0.6rem;
      align-items: center;
      margin-bottom: 1.6rem;
    }
    .controls input, .controls select {
      border: 1px solid var(--hairline-strong);
      background: #fff;
      color: var(--ink-1);
      border-radius: 12px;
      padding: 0.62rem 0.95rem;
      font: inherit;
      font-size: 0.85rem;
      transition: border-color 0.15s ease, box-shadow 0.15s ease;
    }
    .controls input { min-width: 14rem; }
    .controls input::placeholder { color: var(--ink-4); }
    .controls input:focus, .controls select:focus {
      outline: none;
      border-color: var(--teal);
      box-shadow: 0 0 0 3px rgba(6, 189, 180, 0.18);
    }
    .controls .hint { margin-left: auto; font-size: 0.75rem; font-weight: 300; color: var(--ink-4); }
    @media (max-width: 720px) { .controls .hint { display: none; } }

    /* ---------- Bento ---------- */
    .bento {
      display: grid;
      grid-template-columns: repeat(6, 1fr);
      gap: 1.1rem;
    }
    .span-2 { grid-column: span 2; }
    .span-3 { grid-column: span 3; }
    .span-4 { grid-column: span 4; }
    @media (max-width: 1080px) {
      .bento { grid-template-columns: repeat(2, 1fr); }
      .span-2 { grid-column: span 1; }
      .span-3, .span-4 { grid-column: span 2; }
    }
    @media (max-width: 620px) {
      .bento { grid-template-columns: 1fr; }
      .span-2, .span-3, .span-4 { grid-column: span 1; }
    }

    .tile {
      position: relative;
      background: var(--tile);
      border: 1px solid var(--hairline-mid);
      border-radius: 24px;
      box-shadow: var(--shadow-soft);
      overflow: hidden;
      display: flex;
      flex-direction: column;
      transition: box-shadow 0.35s ease, transform 0.35s var(--ease-out), border-color 0.3s ease;
    }
    .tile:hover { box-shadow: var(--shadow-lift); transform: translateY(-3px); }
    .tile.open { border-color: rgba(6, 189, 180, 0.45); }
    .tile-head {
      position: relative;
      display: block;
      width: 100%;
      padding: 1.8rem 1.8rem 1.65rem;
      background: none;
      border: 0;
      font: inherit;
      color: inherit;
      text-align: left;
      cursor: pointer;
    }
    .tile-wm {
      position: absolute;
      right: 1.15rem;
      bottom: 0.35rem;
      font-size: 5.6rem;
      font-weight: 700;
      letter-spacing: -0.05em;
      line-height: 1;
      color: rgba(35, 39, 61, 0.05);
      pointer-events: none;
      user-select: none;
    }
    .tile-top { display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; }
    .tile-stage {
      font-size: 0.72rem;
      font-weight: 600;
      letter-spacing: 0.18em;
      text-transform: uppercase;
      color: var(--teal-dark);
    }
    .tile-chevron {
      flex: none;
      width: 26px;
      height: 26px;
      border-radius: 50%;
      border: 1px solid var(--hairline-strong);
      display: grid;
      place-items: center;
      transition: transform 0.4s var(--spring), background 0.2s ease, border-color 0.2s ease;
    }
    .tile-chevron::before {
      content: "";
      width: 7px;
      height: 7px;
      border-right: 1.5px solid var(--slate);
      border-bottom: 1.5px solid var(--slate);
      transform: rotate(45deg) translate(-1px, -1px);
    }
    .tile.open .tile-chevron {
      transform: rotate(180deg);
      background: rgba(6, 189, 180, 0.09);
      border-color: rgba(6, 189, 180, 0.45);
    }
    .tile-count {
      display: block;
      margin-top: 1rem;
      font-size: 2.6rem;
      font-weight: 700;
      letter-spacing: -0.045em;
      line-height: 1;
      color: var(--navy);
    }
    .tile-count em {
      font-style: normal;
      font-size: 0.85rem;
      font-weight: 400;
      letter-spacing: 0;
      color: var(--ink-3);
      margin-left: 0.35rem;
    }
    .tile-preview {
      display: block;
      margin-top: 0.75rem;
      font-size: 0.82rem;
      font-weight: 300;
      line-height: 1.55;
      color: var(--ink-3);
    }
    .tile-match {
      display: block;
      margin-top: 0.4rem;
      font-family: var(--mono);
      font-size: 0.66rem;
      letter-spacing: 0.06em;
      color: var(--teal-dark);
      min-height: 0.9rem;
    }
    .tile-body {
      max-height: 0;
      overflow: hidden;
      transition: max-height 0.55s var(--ease-out);
    }
    .tile.open .tile-body { max-height: 26rem; overflow-y: auto; }
    .agent-list {
      list-style: none;
      margin: 0 1rem 1rem;
      padding: 0.4rem 0 0.2rem;
      border-top: 1px solid var(--hairline);
      display: flex;
      flex-direction: column;
    }
    .agent-list li + li { border-top: 1px solid var(--hairline); }
    .agent-row {
      width: 100%;
      min-height: 2.9rem;
      display: flex;
      align-items: center;
      gap: 0.65rem;
      padding: 0.72rem 0.6rem;
      border: 0;
      background: none;
      border-radius: 8px;
      font: inherit;
      text-align: left;
      color: inherit;
      cursor: pointer;
      transition: background 0.15s ease;
    }
    .agent-row:hover { background: rgba(6, 189, 180, 0.07); }
    .a-dot { flex: none; width: 7px; height: 7px; border-radius: 50%; background: var(--teal); }
    .a-dot.stub { background: transparent; border: 1.5px dashed var(--mid); }
    .a-id { flex: none; min-width: 2.1rem; font-family: var(--mono); font-size: 0.74rem; color: var(--teal-dark); }
    .a-name { flex: 1; font-size: 0.88rem; font-weight: 500; color: var(--ink-2); line-height: 1.35; }
    .a-status {
      flex: none;
      font-family: var(--mono);
      font-size: 0.6rem;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--ink-4);
    }

    /* ---------- Workflows ---------- */
    .wf-row {
      display: grid;
      grid-template-columns: 13rem 1fr;
      gap: 1.5rem;
      align-items: start;
      padding: 1.7rem 0.75rem;
      margin: 0 -0.75rem;
      border-top: 1px solid var(--hairline);
      border-radius: 14px;
      transition: background 0.4s ease;
    }
    .wf-row.featured {
      grid-template-columns: 1fr;
      gap: 1.3rem;
      background: #fff;
      border: 1px solid var(--hairline-mid);
      border-radius: 24px;
      box-shadow: var(--shadow-soft);
      padding: 2.1rem 2.2rem 2.3rem;
      margin: 0 0 1.6rem;
    }
    .wf-row.flash { background: rgba(6, 189, 180, 0.08); }
    .wf-name {
      display: block;
      font-family: var(--mono);
      font-size: 0.92rem;
      font-weight: 600;
      color: var(--navy);
    }
    .wf-name::before {
      content: "";
      display: inline-block;
      width: 8px;
      height: 8px;
      border-radius: 2px;
      margin-right: 0.5rem;
      background: var(--mid);
    }
    .wf-row.featured .wf-name { color: var(--teal-dark); font-size: 1.06rem; }
    .wf-row.featured .wf-name::before { background: var(--teal); }
    .wf-count {
      display: block;
      margin-top: 0.45rem;
      font-size: 0.75rem;
      font-weight: 300;
      color: var(--ink-4);
    }
    .wf-path { display: flex; flex-wrap: wrap; align-items: center; gap: 0.5rem 0.25rem; }
    .wf-row.featured .wf-path { gap: 0.65rem 0.3rem; }
    .wf-chip {
      display: inline-flex;
      align-items: center;
      gap: 0.45rem;
      border: 1px solid var(--hairline-strong);
      background: #fff;
      border-radius: 12px;
      padding: 0.5rem 0.95rem;
      font: inherit;
      font-size: 0.8rem;
      font-weight: 500;
      color: var(--ink-2);
      cursor: pointer;
      transition: border-color 0.2s ease, color 0.2s ease, box-shadow 0.25s ease, transform 0.3s var(--spring);
    }
    .wf-row.featured .wf-chip { padding: 0.58rem 1.05rem; font-size: 0.85rem; }
    .wf-chip:hover {
      border-color: var(--teal);
      color: var(--navy);
      box-shadow: 0 8px 20px -8px rgba(6, 189, 180, 0.5);
      transform: translateY(-1px);
    }
    .wf-chip .wf-id { font-family: var(--mono); font-size: 0.68rem; color: var(--teal-dark); }
    .wf-link {
      flex: none;
      width: 1.35rem;
      height: 1px;
      background: linear-gradient(90deg, rgba(6, 189, 180, 0.15), rgba(6, 189, 180, 0.65));
      position: relative;
    }
    .wf-link::after {
      content: "";
      position: absolute;
      right: 0;
      top: 50%;
      width: 5px;
      height: 5px;
      border-top: 1px solid rgba(0, 166, 146, 0.85);
      border-right: 1px solid rgba(0, 166, 146, 0.85);
      transform: translateY(-50%) rotate(45deg);
    }
    @media (max-width: 860px) {
      .wf-row { grid-template-columns: 1fr; gap: 0.9rem; }
    }

    /* ---------- Detail panel ---------- */
    .scrim {
      position: fixed;
      inset: 0;
      z-index: 240;
      background: rgba(35, 39, 61, 0.28);
      backdrop-filter: blur(3px);
      -webkit-backdrop-filter: blur(3px);
      opacity: 0;
      transition: opacity 0.3s ease;
    }
    .scrim.show { opacity: 1; }
    .panel {
      position: fixed;
      top: 0;
      right: 0;
      bottom: 0;
      z-index: 260;
      width: min(26rem, 94vw);
      background: #fff;
      border-left: 1px solid var(--hairline);
      box-shadow: -32px 0 90px -30px rgba(35, 39, 61, 0.35);
      transform: translateX(104%);
      transition: transform 0.55s var(--spring);
      overflow-y: auto;
    }
    .panel.open { transform: none; }
    .panel-inner { padding: 2.4rem 1.8rem 3rem; }
    .panel-close {
      position: absolute;
      top: 1rem;
      right: 1rem;
      width: 32px;
      height: 32px;
      border-radius: 50%;
      border: 1px solid var(--hairline-strong);
      background: #fff;
      color: var(--slate);
      font-size: 1.05rem;
      line-height: 1;
      cursor: pointer;
      transition: border-color 0.2s ease, color 0.2s ease, transform 0.3s var(--spring);
    }
    .panel-close:hover { border-color: var(--teal); color: var(--teal-dark); transform: rotate(90deg); }
    .p-id {
      font-family: var(--mono);
      font-size: 0.75rem;
      letter-spacing: 0.06em;
      color: var(--teal-dark);
      margin-bottom: 0.5rem;
    }
    .panel h3 {
      margin: 0 2rem 0.8rem 0;
      font-size: 1.45rem;
      font-weight: 700;
      letter-spacing: -0.025em;
      line-height: 1.15;
      color: var(--navy);
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 0.4rem;
      font-family: var(--mono);
      font-size: 0.64rem;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: var(--ink-3);
      margin-bottom: 1.4rem;
    }
    .badge i {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: var(--teal);
      box-shadow: 0 0 0 3px rgba(6, 189, 180, 0.18);
    }
    .badge.stub i { background: transparent; border: 1.5px dashed var(--mid); box-shadow: none; }
    .panel dl {
      margin: 0;
      display: grid;
      grid-template-columns: 4.6rem 1fr;
      gap: 0.5rem 0.75rem;
      font-size: 0.83rem;
      padding: 1.1rem 0;
      border-top: 1px solid var(--hairline);
      border-bottom: 1px solid var(--hairline);
    }
    .panel dt { color: var(--ink-4); font-weight: 400; }
    .panel dd { margin: 0; color: var(--ink-2); word-break: break-word; }
    .panel code { font-family: var(--mono); font-size: 0.7rem; color: var(--teal-dark); }
    .p-label {
      margin: 1.5rem 0 0.55rem;
      font-size: 0.68rem;
      font-weight: 600;
      letter-spacing: 0.16em;
      text-transform: uppercase;
      color: var(--ink-4);
    }
    .mini-pills { display: flex; flex-wrap: wrap; gap: 0.35rem; }
    .mini-pill {
      border: 1px solid rgba(6, 189, 180, 0.4);
      background: rgba(6, 189, 180, 0.06);
      color: var(--teal-dark);
      border-radius: 10px;
      padding: 0.34rem 0.75rem;
      font-family: var(--mono);
      font-size: 0.68rem;
      cursor: pointer;
      transition: background 0.15s ease, border-color 0.15s ease;
    }
    .mini-pill:hover { background: rgba(6, 189, 180, 0.14); border-color: var(--teal); }
    .p-dim { margin: 0; font-size: 0.8rem; font-weight: 300; color: var(--ink-4); }
    .conn-list { margin: 0; padding: 0; list-style: none; display: flex; flex-direction: column; gap: 0.4rem; }
    .conn-list li { font-family: var(--mono); font-size: 0.74rem; color: var(--ink-3); }
    .conn-list .dir { color: var(--teal); }
    .conn-list button {
      background: none;
      border: none;
      padding: 0;
      font: inherit;
      color: var(--teal-dark);
      cursor: pointer;
    }
    .conn-list button:hover { text-decoration: underline; }
    .conn-list .c-kind { color: var(--ink-4); }

    /* ---------- Footer ---------- */
    footer {
      border-top: 1px solid var(--hairline);
      padding: 2.4rem 0 3.2rem;
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 0.6rem 1.5rem;
      justify-content: space-between;
      font-size: 0.78rem;
      font-weight: 300;
      color: var(--ink-3);
    }
    footer .brand img { width: 20px; height: 20px; }
    footer .brand-name { font-size: 0.95rem; }
    footer .gen { font-family: var(--mono); font-size: 0.66rem; color: var(--ink-4); }
    footer code { font-family: var(--mono); }

    @media (prefers-reduced-motion: reduce) {
      html { scroll-behavior: auto; }
      *, *::before, *::after {
        animation: none !important;
        transition: none !important;
      }
      [data-reveal] { opacity: 1; transform: none; }
    }
  </style>
</head>
<body>
  <nav class="nav" id="nav">
    <div class="nav-inner">
      <a class="brand" href="https://telivity.app" aria-label="Telivity">
        <img src="assets/telivity/logo-1color.svg" width="26" height="26" alt="" />
        <span class="brand-name">Telivity</span>
      </a>
      <div class="nav-links">
        <a href="#journey">Journey</a>
        <a href="#agents">Agents</a>
        <a href="#workflows">Workflows</a>
        <a class="ext" href="https://telivity.app">telivity.app ↗</a>
      </div>
    </div>
  </nav>

  <header class="hero">
    <div class="hero-stage" aria-hidden="true">
      <div class="hero-watermark">Otaip</div>
      <div class="orb orb-a"></div>
      <div class="orb orb-b"></div>
      <div class="orb orb-c"></div>
      <div class="horizon"></div>
    </div>
    <div class="hero-inner">
      <div class="hero-brand" data-reveal style="--i:0">
        <img class="hero-mark" src="assets/telivity/logo-1color.svg" width="76" height="76" alt="Telivity" />
        <span class="hero-wordmark">Telivity</span>
      </div>
      <p class="eyebrow" data-reveal style="--i:1">Otaip · Open Travel AI Platform</p>
      <h1 data-reveal style="--i:2">Search to settlement,<br /><span class="grad">agent by agent.</span></h1>
      <p class="lede" data-reveal style="--i:3">${graph.total_nodes} typed agents. One shared contract. From first search to final settlement.</p>
      <div class="cta" data-reveal style="--i:4">
        <a class="btn btn-primary" href="#agents">Explore the agents</a>
        <a class="btn btn-ghost" href="#journey">See the journey <span class="arr" aria-hidden="true">→</span></a>
      </div>
    </div>
  </header>

  <section class="section alt" id="journey">
    <div class="shell">
      <div class="s-head" data-reveal>
        <p class="eyebrow">The journey</p>
        <h2>One trip. Six acts.</h2>
        <p class="sub">Six stages own every booking — pick an act to meet its agents.</p>
      </div>
      <div class="journey-track">
${journeyHtml}
      </div>
    </div>
  </section>

  <section class="section" id="agents">
    <div class="shell">
      <div class="s-head" data-reveal>
        <p class="eyebrow">The system</p>
        <h2>${graph.total_nodes} agents. ${stages.length} stages.</h2>
        <p class="sub">Open a stage to meet its agents — select any agent for the full picture.</p>
      </div>
      <div class="controls" data-reveal>
        <input id="search" type="search" placeholder="Search by id or name…" aria-label="Search agents" />
        <select id="stage-filter" aria-label="Filter by stage">
          <option value="all">All stages</option>
        </select>
        <select id="status-filter" aria-label="Filter by status">
          <option value="all">All status</option>
          <option value="active">Active</option>
          <option value="stub">Stub</option>
        </select>
        <span class="hint">Filters open matching stages automatically.</span>
      </div>
      <div class="bento" id="bento">
${tilesHtml}
      </div>
    </div>
  </section>

  <section class="section alt" id="workflows">
    <div class="shell">
      <div class="s-head" data-reveal>
        <p class="eyebrow">Workflows</p>
        <h2>Composed, not wired.</h2>
        <p class="sub">The Orchestrator&rsquo;s pipelines, end to end — every step an agent you can inspect.</p>
      </div>
      <div class="wf-list">
${wfRowsHtml}
      </div>
    </div>
  </section>

  <div class="shell">
    <footer>
      <a class="brand" href="https://telivity.app">
        <img src="assets/telivity/logo-1color.svg" width="20" height="20" alt="" />
        <span class="brand-name">Telivity</span>
      </a>
      <span>AI travel infrastructure · Otaip open core · ${graph.total_nodes} agents · ${stages.length} stages · ${workflows.length} workflows</span>
      <span class="gen">generated from <code>agents.graph.json</code> · <code>pnpm gen:agent-map</code></span>
    </footer>
  </div>

  <div class="scrim" id="scrim" hidden></div>
  <aside class="panel" id="panel" aria-hidden="true" aria-label="Agent detail">
    <button type="button" class="panel-close" id="panel-close" aria-label="Close">×</button>
    <div class="panel-inner" id="panel-content"></div>
  </aside>

  <script id="graph-data" type="application/json">${payload.replace(/</g, '\\u003c')}</script>
  <script>
    const graph = JSON.parse(document.getElementById('graph-data').textContent);
    const STAGE_NAMES = ${stageNamesJson};
    const nodesById = {};
    for (const n of graph.nodes) nodesById[n.id] = n;

    const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    const revealEls = Array.from(document.querySelectorAll('[data-reveal]'));
    function revealInViewport() {
      const vh = window.innerHeight || document.documentElement.clientHeight;
      for (const el of revealEls) {
        if (el.classList.contains('in')) continue;
        const r = el.getBoundingClientRect();
        if (r.top < vh * 0.94 && r.bottom > 0) el.classList.add('in');
      }
    }
    if (reduceMotion || !('IntersectionObserver' in window)) {
      for (const el of revealEls) el.classList.add('in');
    } else {
      const io = new IntersectionObserver((entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            entry.target.classList.add('in');
            io.unobserve(entry.target);
          }
        }
      }, { threshold: 0.1, rootMargin: '0px 0px -6% 0px' });
      for (const el of revealEls) io.observe(el);
      revealInViewport();
    }

    const nav = document.getElementById('nav');
    const onScroll = () => { nav.classList.toggle('scrolled', window.scrollY > 10); };
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();

    function escape(s) {
      return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }

    for (const head of document.querySelectorAll('.tile-head')) {
      head.addEventListener('click', () => {
        const tile = head.closest('.tile');
        const open = tile.classList.toggle('open');
        head.setAttribute('aria-expanded', open ? 'true' : 'false');
      });
    }

    function openStageTile(stage) {
      const tile = document.getElementById('tile-' + stage);
      if (!tile) return;
      tile.classList.add('open');
      const head = tile.querySelector('.tile-head');
      if (head) head.setAttribute('aria-expanded', 'true');
      tile.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'center' });
    }
    for (const step of document.querySelectorAll('[data-stage-target]')) {
      step.addEventListener('click', () => openStageTile(step.dataset.stageTarget));
    }

    function workflowsFor(id) {
      const set = new Set();
      for (const e of graph.edges) {
        if (e.kind === 'workflow' && (e.source === id || e.target === id)) set.add(e.label);
      }
      return Array.from(set).sort();
    }
    function neighbors(id) {
      const up = [], down = [];
      for (const e of graph.edges) {
        if (e.source === id) down.push(e);
        if (e.target === id) up.push(e);
      }
      return { up, down };
    }

    const panel = document.getElementById('panel');
    const scrim = document.getElementById('scrim');
    const panelContent = document.getElementById('panel-content');
    let panelOpen = false;

    function openPanel(id) {
      const n = nodesById[id];
      if (!n) return;
      const wfs = workflowsFor(id);
      const nb = neighbors(id);
      let html = '';
      html += '<div class="p-id">' + escape(n.id) + '</div>';
      html += '<h3>' + escape(n.name) + '</h3>';
      html += '<div class="badge' + (n.contract_status === 'stub' ? ' stub' : '') + '"><i></i>' + escape(n.contract_status) + '</div>';
      html += '<dl>';
      html += '<dt>Stage</dt><dd>' + escape(STAGE_NAMES[n.stage] || n.stage) + '</dd>';
      html += '<dt>Version</dt><dd>' + escape(n.version) + '</dd>';
      html += '<dt>Contract</dt><dd>' + (n.has_contract ? 'Yes' : 'No') + '</dd>';
      html += '<dt>Source</dt><dd><code>' + escape(n.source_path) + '</code></dd>';
      html += '</dl>';
      html += '<div class="p-label">Workflows</div>';
      if (wfs.length) {
        html += '<div class="mini-pills">';
        for (const w of wfs) {
          html += '<button type="button" class="mini-pill" data-wf-jump="' + escape(w) + '">' + escape(w) + '</button>';
        }
        html += '</div>';
      } else {
        html += '<p class="p-dim">Not part of a built-in workflow.</p>';
      }
      html += '<div class="p-label">Connections</div><ul class="conn-list">';
      for (const e of nb.up) {
        html += '<li><span class="dir">&larr;</span> <button type="button" data-jump="' + escape(e.source) + '">' + escape(e.source) + '</button> <span class="c-kind">' + escape(e.kind === 'workflow' ? e.label : 'package') + '</span></li>';
      }
      for (const e of nb.down) {
        html += '<li><span class="dir">&rarr;</span> <button type="button" data-jump="' + escape(e.target) + '">' + escape(e.target) + '</button> <span class="c-kind">' + escape(e.kind === 'workflow' ? e.label : 'package') + '</span></li>';
      }
      if (!nb.up.length && !nb.down.length) html += '<li class="p-dim">No graph edges.</li>';
      html += '</ul>';
      panelContent.innerHTML = html;
      panel.classList.add('open');
      panel.setAttribute('aria-hidden', 'false');
      scrim.hidden = false;
      requestAnimationFrame(() => scrim.classList.add('show'));
      panelOpen = true;
      document.getElementById('panel-close').focus({ preventScroll: true });
    }
    function closePanel() {
      if (!panelOpen) return;
      panel.classList.remove('open');
      panel.setAttribute('aria-hidden', 'true');
      scrim.classList.remove('show');
      panelOpen = false;
      setTimeout(() => { if (!panelOpen) scrim.hidden = true; }, 350);
    }
    document.getElementById('panel-close').addEventListener('click', closePanel);
    scrim.addEventListener('click', closePanel);
    document.addEventListener('keydown', (ev) => { if (ev.key === 'Escape') closePanel(); });

    for (const btn of document.querySelectorAll('[data-agent]')) {
      btn.addEventListener('click', (ev) => {
        ev.stopPropagation();
        openPanel(btn.dataset.agent);
      });
    }

    panelContent.addEventListener('click', (ev) => {
      const jump = ev.target.closest('[data-jump]');
      if (jump) { openPanel(jump.dataset.jump); return; }
      const wfJump = ev.target.closest('[data-wf-jump]');
      if (wfJump) {
        const row = document.querySelector('.wf-row[data-wf="' + CSS.escape(wfJump.dataset.wfJump) + '"]');
        closePanel();
        if (row) {
          row.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'center' });
          row.classList.add('flash');
          setTimeout(() => row.classList.remove('flash'), 1600);
        }
      }
    });

    const searchEl = document.getElementById('search');
    const stageEl = document.getElementById('stage-filter');
    const statusEl = document.getElementById('status-filter');
    for (const tile of document.querySelectorAll('.tile')) {
      const o = document.createElement('option');
      o.value = tile.dataset.stage;
      o.textContent = tile.querySelector('.tile-stage').textContent;
      stageEl.appendChild(o);
    }
    function applyFilters() {
      const q = searchEl.value.trim().toLowerCase();
      const st = stageEl.value;
      const ss = statusEl.value;
      const filtering = q !== '' || st !== 'all' || ss !== 'all';
      for (const tile of document.querySelectorAll('.tile')) {
        const rows = tile.querySelectorAll('.agent-row');
        let matches = 0;
        for (const row of rows) {
          const n = nodesById[row.dataset.agent];
          let show = true;
          if (st !== 'all' && n.stage !== st) show = false;
          if (ss !== 'all' && n.contract_status !== ss) show = false;
          if (q && n.id.toLowerCase().indexOf(q) === -1 && n.name.toLowerCase().indexOf(q) === -1) show = false;
          row.parentElement.style.display = show ? '' : 'none';
          if (show) matches++;
        }
        tile.style.display = filtering && matches === 0 ? 'none' : '';
        const head = tile.querySelector('.tile-head');
        if (filtering && matches > 0) {
          tile.classList.add('open');
          head.setAttribute('aria-expanded', 'true');
        }
        const note = tile.querySelector('.tile-match');
        if (note) note.textContent = filtering ? matches + ' of ' + rows.length : '';
      }
    }
    searchEl.addEventListener('input', applyFilters);
    stageEl.addEventListener('change', applyFilters);
    statusEl.addEventListener('change', applyFilters);
  </script>
</body>
</html>
`;
}

function main(): void {
  const repo = repoRoot();
  const graphPath = join(repo, GRAPH_PATH);
  if (!existsSync(graphPath)) {
    console.error(`${GRAPH_PATH} missing. Run \`pnpm gen:manifest\` first.`);
    process.exit(1);
  }
  const graph = JSON.parse(readFileSync(graphPath, 'utf8')) as AgentGraph;
  const html = renderAgentMapHtml(graph);
  const out = join(repo, MAP_HTML_PATH);
  writeFileSync(out, html);
  console.log(`Wrote ${MAP_HTML_PATH} (${graph.total_nodes} agents).`);
}

const isDirect =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirect) {
  main();
}
