#!/usr/bin/env tsx
/**
 * Render `docs/agent-map.html` from an AgentGraph.
 *
 * Telivity-branded mission-control board: dark slate + cyan, Space Grotesk /
 * IBM Plex, workflow edges above cards with side anchors so connections are
 * actually readable. Generated by `pnpm gen:manifest` / `pnpm gen:agent-map`.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AgentGraph, AgentGraphNode } from './agent-graph.js';

const GRAPH_PATH = 'agents.graph.json';
const MAP_HTML_PATH = 'docs/agent-map.html';

const STAGE_ORDER = [
  'reference',
  'search',
  'pricing',
  'booking',
  'ticketing',
  'exchange',
  'settlement',
  'reconciliation',
  'tmc',
  'platform',
  'core',
  'lodging',
] as const;

function repoRoot(): string {
  let cur = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(cur, 'pnpm-workspace.yaml'))) return cur;
    const parent = dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return resolve(dirname(fileURLToPath(import.meta.url)), '..');
}

function compareAgentIds(a: string, b: string): number {
  const [aMajor = 0, aMinor = 0] = a.split('.').map(Number);
  const [bMajor = 0, bMinor = 0] = b.split('.').map(Number);
  return aMajor - bMajor || aMinor - bMinor || a.localeCompare(b);
}

function stageSortKey(stage: string): number {
  const idx = (STAGE_ORDER as readonly string[]).indexOf(stage);
  return idx === -1 ? 1000 : idx;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function groupByStage(nodes: readonly AgentGraphNode[]): Array<[string, AgentGraphNode[]]> {
  const map = new Map<string, AgentGraphNode[]>();
  for (const n of nodes) {
    const list = map.get(n.stage) ?? [];
    list.push(n);
    map.set(n.stage, list);
  }
  for (const list of map.values()) {
    list.sort((a, b) => compareAgentIds(a.id, b.id));
  }
  return [...map.entries()].sort(([a], [b]) => stageSortKey(a) - stageSortKey(b) || a.localeCompare(b));
}

export function renderAgentMapHtml(graph: AgentGraph): string {
  const stages = groupByStage(graph.nodes);
  const workflows = [
    ...new Set(graph.edges.filter((e) => e.kind === 'workflow').map((e) => e.label)),
  ].sort();

  const columnsHtml = stages
    .map(([stage, agents], colIdx) => {
      const cards = agents
        .map((a, cardIdx) => {
          const status = a.contract_status === 'active' ? 'active' : 'stub';
          const delay = colIdx * 45 + cardIdx * 18;
          return `        <button type="button" class="node ${status}" data-id="${escapeHtml(a.id)}" data-stage="${escapeHtml(a.stage)}" style="animation-delay:${delay}ms" title="${escapeHtml(a.name)}">
          <span class="id">${escapeHtml(a.id)}</span>
          <span class="name">${escapeHtml(a.name)}</span>
        </button>`;
        })
        .join('\n');
      return `      <section class="stage" data-stage="${escapeHtml(stage)}">
        <h2><span class="stage-label">${escapeHtml(stage)}</span> <span class="count">${agents.length}</span></h2>
        <div class="nodes">
${cards}
        </div>
      </section>`;
    })
    .join('\n');

  const workflowPills = [
    `<button type="button" class="pill" data-workflow="all">All</button>`,
    ...workflows.map(
      (w) =>
        `<button type="button" class="pill" data-workflow="${escapeHtml(w)}">${escapeHtml(w)}</button>`,
    ),
  ].join('\n        ');

  const payload = JSON.stringify(graph);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Otaip Agent Map · Telivity</title>
  <meta name="description" content="Telivity Otaip — mission-control map of travel AI agents from search to settlement." />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet" />
  <style>
    :root {
      --bg-0: #020617;
      --bg-1: #070d1c;
      --panel: rgba(15, 23, 42, 0.66);
      --panel-solid: #0f172a;
      --hairline: rgba(148, 163, 184, 0.10);
      --hairline-strong: rgba(148, 163, 184, 0.18);
      --cyan-200: #a5f3fc;
      --cyan-300: #67e8f9;
      --cyan-400: #22d3ee;
      --cyan-500: #06b6d4;
      --cyan-glow: rgba(34, 211, 238, 0.16);
      --cyan-dim: rgba(34, 211, 238, 0.08);
      --pkg: #64748b;
      --pkg-hi: #94a3b8;
      --ink-1: #f1f5f9;
      --ink-2: #cbd5e1;
      --ink-3: #94a3b8;
      --ink-4: #64748b;
      --card-bg: linear-gradient(180deg, #101b31 0%, #0c1424 100%);
      --card-border: rgba(148, 163, 184, 0.14);
      --card-bg-hot: linear-gradient(180deg, #14233f 0%, #0e1930 100%);
    }
    * { box-sizing: border-box; }
    html, body { margin: 0; min-height: 100%; }
    body {
      font-family: "IBM Plex Sans", system-ui, sans-serif;
      color: var(--ink-1);
      background:
        radial-gradient(1100px 520px at 12% -10%, rgba(6, 182, 212, 0.10), transparent 60%),
        radial-gradient(900px 600px at 105% 110%, rgba(29, 78, 216, 0.07), transparent 55%),
        var(--bg-0);
      -webkit-font-smoothing: antialiased;
    }
    a { color: var(--cyan-400); text-decoration: none; }
    a:hover { text-decoration: underline; }

    .shell { max-width: 1440px; margin: 0 auto; padding: 0 1.5rem 2rem; }

    header.hero {
      padding: 1.75rem 0 1rem;
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 1rem 2rem;
      align-items: end;
    }
    @media (max-width: 900px) {
      header.hero { grid-template-columns: 1fr; }
    }
    .eyebrow {
      margin: 0 0 0.75rem;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.68rem;
      font-weight: 500;
      letter-spacing: 0.16em;
      text-transform: uppercase;
      color: var(--cyan-400);
    }
    .eyebrow a { color: inherit; }
    h1 {
      margin: 0;
      font-family: "Space Grotesk", system-ui, sans-serif;
      font-weight: 700;
      font-size: clamp(2.1rem, 4.2vw, 3.25rem);
      letter-spacing: -0.035em;
      line-height: 1.05;
      max-width: 18ch;
    }
    h1 span { color: var(--cyan-400); }
    .lede {
      margin: 0.75rem 0 0;
      color: var(--ink-3);
      font-size: 0.95rem;
      max-width: 38rem;
      line-height: 1.5;
    }
    .stats {
      display: grid;
      grid-template-columns: repeat(2, auto);
      gap: 0.55rem 1.25rem;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.68rem;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--ink-4);
      text-align: right;
    }
    .stats strong {
      display: block;
      color: var(--ink-1);
      font-size: 1.05rem;
      letter-spacing: -0.02em;
      font-family: "Space Grotesk", system-ui, sans-serif;
      font-weight: 600;
      text-transform: none;
    }

    .toolbar {
      position: sticky;
      top: 0;
      z-index: 50;
      display: flex;
      flex-wrap: wrap;
      gap: 0.55rem;
      align-items: center;
      padding: 0.7rem 0;
      margin-bottom: 0.85rem;
      background: rgba(2, 6, 23, 0.72);
      backdrop-filter: blur(14px);
      -webkit-backdrop-filter: blur(14px);
      border-bottom: 1px solid var(--hairline-strong);
    }
    .toolbar input, .toolbar select {
      border: 1px solid rgba(148, 163, 184, 0.18);
      background: rgba(2, 6, 23, 0.85);
      color: var(--ink-1);
      border-radius: 8px;
      padding: 0.45rem 0.65rem;
      font: inherit;
      font-size: 0.82rem;
    }
    .toolbar input { min-width: 11rem; font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 0.75rem; }
    .toolbar input::placeholder { color: var(--ink-4); }
    .toolbar input:focus, .toolbar select:focus {
      outline: none;
      border-color: var(--cyan-500);
      box-shadow: 0 0 0 1px rgba(6, 182, 212, 0.35);
    }
    .toolbar select option { background: #0f172a; }
    .pills {
      display: flex;
      flex-wrap: wrap;
      gap: 0.35rem;
      align-items: center;
    }
    .pill {
      border: 1px solid rgba(148, 163, 184, 0.16);
      background: transparent;
      color: var(--ink-3);
      border-radius: 999px;
      padding: 0.32rem 0.7rem;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.68rem;
      letter-spacing: 0.02em;
      cursor: pointer;
      transition: border-color .15s, color .15s, background .15s;
    }
    .pill:hover { border-color: rgba(34, 211, 238, 0.4); color: var(--ink-2); }
    .pill.active {
      border-color: var(--cyan-400);
      color: var(--cyan-300);
      background: var(--cyan-dim);
    }
    .legend {
      display: flex;
      flex-wrap: wrap;
      gap: 0.75rem;
      margin-left: auto;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.62rem;
      letter-spacing: 0.06em;
      text-transform: uppercase;
      color: var(--ink-4);
    }
    .legend span::before {
      content: "";
      display: inline-block;
      width: 0.7rem;
      height: 0.7rem;
      border-radius: 2px;
      margin-right: 0.3rem;
      vertical-align: -1px;
    }
    .legend .l-active::before { background: var(--cyan-500); box-shadow: 0 0 8px rgba(6,182,212,.45); }
    .legend .l-stub::before { background: #475569; border: 1px dashed #94a3b8; }
    .legend .l-wf::before { background: var(--cyan-400); }
    .legend .l-pkg::before { background: transparent; border: 1px dashed var(--pkg-hi); }

    .layout {
      display: grid;
      grid-template-columns: 1fr minmax(16rem, 18.5rem);
      gap: 1.25rem;
    }
    @media (max-width: 960px) {
      .layout { grid-template-columns: 1fr; }
    }

    .board-wrap {
      position: relative;
      overflow-x: auto;
      overflow-y: hidden;
      border: 1px solid var(--hairline-strong);
      border-radius: 16px;
      min-height: 30rem;
      background:
        linear-gradient(rgba(148,163,184,0.045) 1px, transparent 1px),
        linear-gradient(90deg, rgba(148,163,184,0.045) 1px, transparent 1px),
        var(--bg-1);
      background-size: 32px 32px, 32px 32px, auto;
      -webkit-mask-image: radial-gradient(120% 100% at 50% 0%, #000 60%, rgba(0,0,0,0.7));
              mask-image: radial-gradient(120% 100% at 50% 0%, #000 60%, rgba(0,0,0,0.7));
    }
    .board {
      position: relative;
      z-index: 1;
      display: flex;
      gap: 1.1rem;
      padding: 1.1rem 1.1rem 7.5rem;
      min-width: max-content;
    }
    .bus-label {
      position: absolute;
      left: 1.1rem;
      bottom: 4.6rem;
      z-index: 4;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.58rem;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--ink-4);
      pointer-events: none;
    }
    .bus-rule {
      position: absolute;
      left: 1.1rem;
      right: 1.1rem;
      bottom: 5.4rem;
      height: 1px;
      background: var(--hairline);
      z-index: 2;
      pointer-events: none;
    }

    svg.edges {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
      z-index: 3;
      pointer-events: none;
      overflow: visible;
    }
    svg.edges .hit { fill: none; stroke: transparent; stroke-width: 14; pointer-events: stroke; cursor: pointer; }
    svg.edges .glow { fill: none; stroke: var(--cyan-400); stroke-width: 12; opacity: 0.14; stroke-linecap: round; }
    svg.edges .core-wf {
      fill: none;
      stroke: var(--cyan-400);
      stroke-width: 2.75;
      opacity: 0.95;
      stroke-linecap: round;
      stroke-linejoin: round;
    }
    svg.edges .ants {
      fill: none;
      stroke: var(--cyan-200);
      stroke-width: 1.75;
      stroke-linecap: round;
      stroke-dasharray: 2 8;
      animation: march 0.85s linear infinite;
      opacity: 0;
    }
    svg.edges g.live .core-wf { stroke-width: 3.5; opacity: 1; stroke: var(--cyan-300); }
    svg.edges g.live .glow { stroke-width: 16; opacity: 0.22; }
    svg.edges g.live .ants { opacity: 1; }
    svg.edges g.dim .core-wf, svg.edges g.dim .glow, svg.edges g.dim .ants { opacity: 0.08; }
    svg.edges g.dim .core-wf { marker-end: none; }
    svg.edges g.hot .core-wf { stroke-width: 4; opacity: 1; stroke: var(--cyan-200); }
    svg.edges g.hot .glow { opacity: 0.28; stroke-width: 18; }
    svg.edges .core-pkg {
      fill: none;
      stroke: var(--pkg-hi);
      stroke-width: 2;
      opacity: 0.55;
      stroke-dasharray: 4 6;
      stroke-linecap: round;
      stroke-linejoin: round;
    }
    svg.edges g.pkg-dim .core-pkg { opacity: 0.1; marker-end: none; }
    svg.edges g.pkg-hot .core-pkg { stroke: var(--pkg-hi); opacity: 0.9; }
    @keyframes march { to { stroke-dashoffset: -10; } }

    .stage { width: 11.75rem; flex: 0 0 auto; }
    .stage h2 {
      margin: 0 0 0.55rem;
      display: flex;
      align-items: center;
      gap: 0.4rem;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.62rem;
      font-weight: 500;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--ink-4);
    }
    .stage.live-stage h2 .stage-label { color: var(--cyan-300); }
    .stage.live-stage h2::after {
      content: "";
      display: inline-block;
      width: 0.45rem;
      height: 2px;
      margin-left: 0.15rem;
      background: var(--cyan-400);
      box-shadow: 0 0 8px rgba(34,211,238,.6);
    }
    .stage .count {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-width: 1.2rem;
      padding: 0.05rem 0.3rem;
      border-radius: 999px;
      background: rgba(34, 211, 238, 0.08);
      color: var(--cyan-400);
      font-size: 0.58rem;
      letter-spacing: 0;
    }
    .nodes { display: flex; flex-direction: column; gap: 0.4rem; }

    .node {
      position: relative;
      text-align: left;
      border: 1px solid var(--card-border);
      background: var(--card-bg);
      border-radius: 10px;
      padding: 0.5rem 0.6rem 0.5rem 0.7rem;
      cursor: pointer;
      display: flex;
      flex-direction: column;
      gap: 0.12rem;
      color: inherit;
      animation: rise 320ms cubic-bezier(.2,.7,.2,1) both;
      transition: border-color .16s ease, box-shadow .16s ease, opacity .18s ease, transform .16s ease, background .16s ease;
    }
    .node::before {
      content: "";
      position: absolute;
      left: -1px;
      top: 8px;
      bottom: 8px;
      width: 2px;
      border-radius: 2px;
      background: transparent;
    }
    .node .id {
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.66rem;
      font-weight: 500;
      color: var(--ink-4);
      letter-spacing: 0.04em;
    }
    .node .name {
      font-size: 0.78rem;
      line-height: 1.3;
      font-weight: 500;
      color: var(--ink-2);
    }
    .node.active::before { background: var(--cyan-500); box-shadow: 0 0 8px rgba(6,182,212,.5); }
    .node.stub { border-style: dashed; opacity: 0.62; }
    .node.stub::before { background: #475569; }
    .node.stub .name { color: var(--ink-3); }
    .node:hover {
      border-color: rgba(34, 211, 238, 0.5);
      background: var(--card-bg-hot);
      transform: translateX(2px);
    }
    .node.on-path {
      border-color: rgba(34, 211, 238, 0.65);
      background: var(--card-bg-hot);
      box-shadow: inset 0 0 14px rgba(34, 211, 238, 0.06);
    }
    .node.on-path::before { background: var(--cyan-300); }
    .node.on-path .id { color: var(--cyan-300); }
    .node.selected {
      border-color: var(--cyan-400);
      background: var(--card-bg-hot);
      box-shadow: 0 0 0 1px rgba(34, 211, 238, 0.55), 0 0 28px rgba(34, 211, 238, 0.18);
    }
    .node.dim { opacity: 0.22; filter: saturate(0.4); }
    @keyframes rise {
      from { opacity: 0; transform: translateY(6px); }
      to { opacity: 1; transform: translateY(0); }
    }

    .detail {
      border: 1px solid var(--hairline-strong);
      border-radius: 16px;
      background: var(--panel);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      padding: 1.1rem;
      align-self: start;
      position: sticky;
      top: 4.5rem;
      min-height: 16rem;
    }
    .detail .empty {
      margin: 0;
      padding: 1.5rem 0.5rem;
      text-align: center;
      color: var(--ink-4);
      font-size: 0.85rem;
      border: 1px dashed var(--hairline-strong);
      border-radius: 12px;
    }
    .detail .id-chip {
      display: inline-block;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.68rem;
      color: var(--cyan-300);
      letter-spacing: 0.04em;
      margin-bottom: 0.35rem;
    }
    .detail h3 {
      margin: 0 0 0.55rem;
      font-family: "Space Grotesk", system-ui, sans-serif;
      font-size: 1.1rem;
      font-weight: 600;
      letter-spacing: -0.02em;
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 0.35rem;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.62rem;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--ink-3);
      margin-bottom: 0.85rem;
    }
    .badge i {
      width: 0.45rem;
      height: 0.45rem;
      border-radius: 50%;
      background: var(--cyan-500);
      box-shadow: 0 0 8px rgba(6,182,212,.6);
    }
    .badge.stub i { background: #475569; box-shadow: none; }
    .detail dl {
      margin: 0;
      display: grid;
      grid-template-columns: 5.2rem 1fr;
      gap: 0.4rem 0.55rem;
      font-size: 0.78rem;
      padding-top: 0.75rem;
      border-top: 1px solid var(--hairline);
    }
    .detail dt { color: var(--ink-4); }
    .detail dd { margin: 0; color: var(--ink-2); word-break: break-word; }
    .detail code {
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.68rem;
      color: var(--cyan-300);
    }
    .detail .block-label {
      margin: 1rem 0 0.4rem;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.62rem;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: var(--ink-4);
    }
    .detail .mini-pills { display: flex; flex-wrap: wrap; gap: 0.3rem; }
    .detail .conn-list {
      margin: 0;
      padding: 0;
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
    }
    .detail .conn-list li {
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.72rem;
      color: var(--ink-3);
    }
    .detail .conn-list button {
      background: none;
      border: none;
      color: var(--cyan-300);
      font: inherit;
      cursor: pointer;
      padding: 0;
    }
    .detail .conn-list button:hover { text-decoration: underline; }

    footer.note {
      margin-top: 1.25rem;
      padding-top: 0.85rem;
      border-top: 1px solid var(--hairline);
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.68rem;
      color: var(--ink-4);
      letter-spacing: 0.02em;
    }

    @media (prefers-reduced-motion: reduce) {
      *, *::before, *::after {
        animation: none !important;
        transition: none !important;
      }
    }
  </style>
</head>
<body>
  <div class="shell">
    <header class="hero">
      <div>
        <p class="eyebrow"><a href="https://telivity.app">Telivity</a> · Otaip — open source</p>
        <h1>Agent map for the <span>whole travel transaction</span>.</h1>
        <p class="lede">${graph.total_nodes} typed agents. Search to settlement. Solid cyan arcs are Orchestrator workflows; dashed traces are package dependencies.</p>
      </div>
      <div class="stats" aria-label="Graph stats">
        <div><strong>${graph.total_nodes}</strong>Agents</div>
        <div><strong>${stages.length}</strong>Stages</div>
        <div><strong>${workflows.length}</strong>Workflows</div>
        <div><strong>${graph.total_edges}</strong>Edges</div>
      </div>
    </header>

    <div class="toolbar">
      <input id="search" type="search" placeholder="Search id or name…" />
      <select id="stage">
        <option value="all">All stages</option>
      </select>
      <select id="status">
        <option value="all">All status</option>
        <option value="active">Active</option>
        <option value="stub">Stub</option>
      </select>
      <div class="pills" id="workflow-pills" role="group" aria-label="Workflows">
        ${workflowPills}
      </div>
      <div class="legend">
        <span class="l-active">Active</span>
        <span class="l-stub">Stub</span>
        <span class="l-wf">Workflow</span>
        <span class="l-pkg">Package</span>
      </div>
    </div>

    <div class="layout">
      <div class="board-wrap" id="board-wrap">
        <div class="bus-rule" aria-hidden="true"></div>
        <div class="bus-label" aria-hidden="true">Package dependencies</div>
        <svg class="edges" id="edges" aria-hidden="true">
          <defs>
            <marker id="arrow-wf" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
              <path d="M0 0.5 L7.5 4 L0 7.5 Z" fill="#67e8f9"/>
            </marker>
            <marker id="arrow-pkg" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
              <path d="M0 0.5 L7.5 4 L0 7.5 Z" fill="#64748b"/>
            </marker>
          </defs>
        </svg>
        <div class="board" id="board">
${columnsHtml}
        </div>
      </div>
      <aside class="detail" id="detail">
        <p class="empty">Select an agent — or pick a workflow.</p>
      </aside>
    </div>

    <footer class="note">
      <a href="https://telivity.app">Telivity</a> — AI travel infrastructure · Otaip open core ·
      ${graph.total_nodes} agents · ${graph.total_edges} edges · generated from <code>agents.graph.json</code> · <code>pnpm gen:agent-map</code>
    </footer>
  </div>

  <script id="graph-data" type="application/json">${payload.replace(/</g, '\\u003c')}</script>
  <script>
    const graph = JSON.parse(document.getElementById('graph-data').textContent);
    const board = document.getElementById('board');
    const boardWrap = document.getElementById('board-wrap');
    const edgesSvg = document.getElementById('edges');
    const detail = document.getElementById('detail');
    const searchEl = document.getElementById('search');
    const stageEl = document.getElementById('stage');
    const statusEl = document.getElementById('status');
    const pills = document.getElementById('workflow-pills');

    const nodesById = Object.fromEntries(graph.nodes.map(n => [n.id, n]));
    const workflows = [...new Set(graph.edges.filter(e => e.kind === 'workflow').map(e => e.label))].sort();
    for (const s of [...new Set(graph.nodes.map(n => n.stage))].sort()) {
      const o = document.createElement('option');
      o.value = s; o.textContent = s; stageEl.appendChild(o);
    }

    let selected = null;
    let workflow = workflows.includes('full_booking') ? 'full_booking' : (workflows[0] || 'all');
    let hotEdge = null;

    function setActivePill() {
      for (const btn of pills.querySelectorAll('.pill')) {
        btn.classList.toggle('active', btn.dataset.workflow === workflow);
      }
    }
    setActivePill();

    function pathIdsForWorkflow(name) {
      if (name === 'all') return null;
      const ids = new Set();
      for (const e of graph.edges) {
        if (e.kind === 'workflow' && e.label === name) {
          ids.add(e.source); ids.add(e.target);
        }
      }
      return ids;
    }

    function workflowsFor(id) {
      const set = new Set();
      for (const e of graph.edges) {
        if (e.kind === 'workflow' && (e.source === id || e.target === id)) set.add(e.label);
      }
      return [...set].sort();
    }

    function neighbors(id) {
      const up = [], down = [];
      for (const e of graph.edges) {
        if (e.source === id) down.push({ id: e.target, kind: e.kind, label: e.label });
        if (e.target === id) up.push({ id: e.source, kind: e.kind, label: e.label });
      }
      return { up, down };
    }

    function isNeighbor(id, other) {
      return graph.edges.some(e =>
        (e.source === id && e.target === other) || (e.target === id && e.source === other)
      );
    }

    function escape(s) {
      return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    function applyFilters() {
      const q = searchEl.value.trim().toLowerCase();
      const stage = stageEl.value;
      const status = statusEl.value;
      const pathIds = pathIdsForWorkflow(workflow);
      const liveStages = new Set();
      for (const btn of board.querySelectorAll('.node')) {
        const n = nodesById[btn.dataset.id];
        let show = true;
        if (stage !== 'all' && n.stage !== stage) show = false;
        if (status !== 'all' && n.contract_status !== status) show = false;
        if (q && !(n.id.includes(q) || n.name.toLowerCase().includes(q))) show = false;
        if (pathIds && !pathIds.has(n.id)) show = false;
        btn.style.display = show ? '' : 'none';
        const onPath = Boolean(pathIds && pathIds.has(n.id));
        btn.classList.toggle('on-path', onPath);
        btn.classList.toggle('dim', Boolean(selected) && selected !== n.id && !isNeighbor(selected, n.id));
        btn.classList.toggle('selected', selected === n.id);
        if (onPath) liveStages.add(n.stage);
      }
      for (const sec of board.querySelectorAll('.stage')) {
        sec.classList.toggle('live-stage', liveStages.has(sec.dataset.stage));
      }
      drawEdges();
    }

    function showDetail(id) {
      const n = nodesById[id];
      if (!n) {
        detail.innerHTML = '<p class="empty">Select an agent — or pick a workflow.</p>';
        return;
      }
      const wfs = workflowsFor(id);
      const { up, down } = neighbors(id);
      const badgeClass = n.contract_status === 'stub' ? 'badge stub' : 'badge';
      detail.innerHTML = \`
        <div class="id-chip">\${escape(n.id)}</div>
        <h3>\${escape(n.name)}</h3>
        <div class="\${badgeClass}"><i></i>\${escape(n.contract_status)}</div>
        <dl>
          <dt>Stage</dt><dd>\${escape(n.stage)}</dd>
          <dt>Version</dt><dd>\${escape(n.version)}</dd>
          <dt>Contract</dt><dd>\${n.has_contract ? 'yes' : 'no'}</dd>
          <dt>Source</dt><dd><code>\${escape(n.source_path)}</code></dd>
        </dl>
        <div class="block-label">Workflows</div>
        <div class="mini-pills">\${
          wfs.length
            ? wfs.map(w => '<button type="button" class="pill' + (w === workflow ? ' active' : '') + '" data-set-workflow="' + escape(w) + '">' + escape(w) + '</button>').join('')
            : '<span style="color:var(--ink-4);font-size:0.8rem">Not in a built-in workflow.</span>'
        }</div>
        <div class="block-label">Connections</div>
        <ul class="conn-list">
          \${up.map(c => '<li>← <button type="button" data-jump="' + escape(c.id) + '">' + escape(c.id) + '</button> <span>(' + escape(c.kind) + (c.kind === 'workflow' ? ': ' + escape(c.label) : '') + ')</span></li>').join('')}
          \${down.map(c => '<li>→ <button type="button" data-jump="' + escape(c.id) + '">' + escape(c.id) + '</button> <span>(' + escape(c.kind) + (c.kind === 'workflow' ? ': ' + escape(c.label) : '') + ')</span></li>').join('')}
          \${up.length + down.length === 0 ? '<li style="color:var(--ink-4)">No graph edges.</li>' : ''}
        </ul>
      \`;
    }

    function anchors(id) {
      const el = board.querySelector('.node[data-id="' + CSS.escape(id) + '"]');
      if (!el || el.style.display === 'none') return null;
      const a = el.getBoundingClientRect();
      const b = boardWrap.getBoundingClientRect();
      const x0 = a.left - b.left + boardWrap.scrollLeft;
      const y0 = a.top - b.top + boardWrap.scrollTop;
      return {
        l: x0, r: x0 + a.width, t: y0, b: y0 + a.height,
        cy: y0 + a.height / 2,
        stage: el.dataset.stage || el.closest('.stage')?.dataset.stage,
      };
    }

    function wfPath(a, b) {
      if (a.stage === b.stage) {
        return 'M ' + a.r + ' ' + a.cy + ' C ' + (a.r + 14) + ' ' + a.cy + ', ' + (b.r + 14) + ' ' + b.cy + ', ' + b.r + ' ' + b.cy;
      }
      const gap = Math.max(12, b.l - a.r);
      const dx = Math.max(10, gap * 0.45);
      return 'M ' + a.r + ' ' + a.cy + ' C ' + (a.r + dx) + ' ' + a.cy + ', ' + (b.l - dx) + ' ' + b.cy + ', ' + b.l + ' ' + b.cy;
    }

    function pkgPath(a, b, laneY) {
      const gx1 = a.r + 8;
      const gx2 = b.l - 8;
      const r = 6;
      const down1 = a.cy < laneY;
      const up2 = b.cy < laneY;
      const y1a = down1 ? a.cy + r : a.cy - r;
      const y1b = down1 ? laneY - r : laneY + r;
      const y2a = up2 ? laneY - r : laneY + r;
      const y2b = up2 ? b.cy + r : b.cy - r;
      return [
        'M ' + a.r + ' ' + a.cy,
        'H ' + (gx1 - r),
        'Q ' + gx1 + ' ' + a.cy + ' ' + gx1 + ' ' + y1a,
        'V ' + y1b,
        'Q ' + gx1 + ' ' + laneY + ' ' + (gx1 + (gx2 > gx1 ? r : -r)) + ' ' + laneY,
        'H ' + (gx2 - (gx2 > gx1 ? r : -r)),
        'Q ' + gx2 + ' ' + laneY + ' ' + gx2 + ' ' + y2a,
        'V ' + y2b,
        'Q ' + gx2 + ' ' + b.cy + ' ' + (gx2 - r) + ' ' + b.cy,
        'H ' + b.l,
      ].join(' ');
    }

    function stageIndex(stage) {
      const secs = [...board.querySelectorAll('.stage')];
      return secs.findIndex(s => s.dataset.stage === stage);
    }

    function drawEdges() {
      const w = Math.max(boardWrap.scrollWidth, 1);
      const h = Math.max(boardWrap.clientHeight, board.scrollHeight, 1);
      edgesSvg.setAttribute('viewBox', '0 0 ' + w + ' ' + h);
      edgesSvg.style.width = w + 'px';
      edgesSvg.style.height = h + 'px';

      const defs = edgesSvg.querySelector('defs');
      const parts = [defs ? defs.outerHTML : ''];
      const pathIds = pathIdsForWorkflow(workflow);

      const pkgEdges = [];
      for (const e of graph.edges) {
        if (e.kind !== 'package') continue;
        const a = anchors(e.source);
        const b = anchors(e.target);
        if (!a || !b) continue;
        pkgEdges.push({ e, a, b, ti: stageIndex(b.stage) });
      }
      pkgEdges.sort((x, y) => x.ti - y.ti);
      const laneBase = h - 96;

      let pi = 0;
      for (const item of pkgEdges) {
        const laneY = laneBase + (pi % 10) * 8;
        pi++;
        const d = pkgPath(item.a, item.b, laneY);
        const key = item.e.source + '|' + item.e.target + '|' + item.e.label;
        let cls = 'edge-pkg';
        if (workflow !== 'all') cls += ' pkg-dim';
        if (selected && (item.e.source === selected || item.e.target === selected)) cls = 'edge-pkg pkg-hot';
        if (hotEdge === key) cls = 'edge-pkg pkg-hot';
        parts.push(
          '<g class="' + cls + '" data-edge="' + key + '">' +
          '<path class="hit" d="' + d + '" />' +
          '<path class="core-pkg" d="' + d + '" marker-end="url(#arrow-pkg)" />' +
          '</g>'
        );
      }

      for (const e of graph.edges) {
        if (e.kind !== 'workflow') continue;
        if (workflow !== 'all' && e.label !== workflow) continue;
        const a = anchors(e.source);
        const b = anchors(e.target);
        if (!a || !b) continue;
        const d = wfPath(a, b);
        const key = e.source + '|' + e.target + '|' + e.label;
        let cls = 'edge-wf';
        const live = workflow !== 'all' && e.label === workflow;
        if (live) cls += ' live';
        if (selected && !(e.source === selected || e.target === selected) && !live) cls += ' dim';
        if (selected && (e.source === selected || e.target === selected)) cls += ' hot';
        if (hotEdge === key) cls += ' hot';
        const marker = cls.includes('dim') ? '' : ' marker-end="url(#arrow-wf)"';
        const pulse = live
          ? '<circle r="2.5" fill="#a5f3fc"><animateMotion dur="2.2s" repeatCount="indefinite" path="' + d + '"/></circle>'
          : '';
        parts.push(
          '<g class="' + cls + '" data-edge="' + key + '" data-label="' + e.label + '">' +
          '<path class="hit" d="' + d + '" />' +
          '<path class="glow" d="' + d + '" />' +
          '<path class="core-wf" d="' + d + '"' + marker + ' />' +
          '<path class="ants" d="' + d + '" />' +
          pulse +
          '</g>'
        );
      }

      edgesSvg.innerHTML = parts.join('');
    }

    board.addEventListener('click', (ev) => {
      const btn = ev.target.closest('.node');
      if (!btn) return;
      selected = btn.dataset.id;
      showDetail(selected);
      applyFilters();
    });

    detail.addEventListener('click', (ev) => {
      const wfBtn = ev.target.closest('[data-set-workflow]');
      if (wfBtn) {
        workflow = wfBtn.dataset.setWorkflow;
        setActivePill();
        applyFilters();
        if (selected) showDetail(selected);
        return;
      }
      const jump = ev.target.closest('[data-jump]');
      if (jump) {
        selected = jump.dataset.jump;
        showDetail(selected);
        applyFilters();
        const el = board.querySelector('.node[data-id="' + CSS.escape(selected) + '"]');
        el?.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
      }
    });

    pills.addEventListener('click', (ev) => {
      const btn = ev.target.closest('.pill');
      if (!btn) return;
      workflow = btn.dataset.workflow;
      setActivePill();
      applyFilters();
      if (selected) showDetail(selected);
    });

    edgesSvg.addEventListener('pointerover', (ev) => {
      const g = ev.target.closest('g[data-edge]');
      hotEdge = g ? g.dataset.edge : null;
      drawEdges();
    });
    edgesSvg.addEventListener('pointerout', () => {
      hotEdge = null;
      drawEdges();
    });

    searchEl.addEventListener('input', applyFilters);
    stageEl.addEventListener('change', applyFilters);
    statusEl.addEventListener('change', applyFilters);
    boardWrap.addEventListener('scroll', drawEdges);
    window.addEventListener('resize', drawEdges);

    applyFilters();
  </script>
</body>
</html>
`;
}

function main(): void {
  const repo = repoRoot();
  const graphPath = join(repo, GRAPH_PATH);
  if (!existsSync(graphPath)) {
    console.error(`${GRAPH_PATH} missing. Run \`pnpm gen:manifest\` first.`);
    process.exit(1);
  }
  const graph = JSON.parse(readFileSync(graphPath, 'utf8')) as AgentGraph;
  const html = renderAgentMapHtml(graph);
  const out = join(repo, MAP_HTML_PATH);
  writeFileSync(out, html);
  console.log(`Wrote ${MAP_HTML_PATH} (${graph.total_nodes} agents).`);
}

const isDirect =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirect) {
  main();
}
