#!/usr/bin/env tsx
/**
 * Render `docs/agent-map.html` from an AgentGraph.
 *
 * "Connection stage" presentation of the Otaip agent system for Telivity.
 * The first viewport is a working stage, not a marketing hero: a workflow
 * selector renders the chosen Orchestrator pipeline as a horizontal sequence
 * of large agent cells joined by animated connector bars. Below, a quiet
 * bento grid lists every stage and agent — agents on the active path stay
 * lit, the rest dim. Selecting an agent opens its detail and lights its
 * edges and neighbors; package dependencies are shown only for the selected
 * agent. Generated by `pnpm gen:manifest` / `pnpm gen:agent-map`.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AgentGraph, AgentGraphNode } from './agent-graph.js';

const GRAPH_PATH = 'agents.graph.json';
const MAP_HTML_PATH = 'docs/agent-map.html';

const STAGE_ORDER = [
  'reference',
  'search',
  'pricing',
  'booking',
  'ticketing',
  'exchange',
  'settlement',
  'reconciliation',
  'tmc',
  'platform',
  'core',
  'lodging',
] as const;

const STAGE_DISPLAY: Readonly<Record<string, string>> = {
  reference: 'Reference',
  search: 'Search',
  pricing: 'Pricing',
  booking: 'Booking',
  ticketing: 'Ticketing',
  exchange: 'Exchange',
  settlement: 'Settlement',
  reconciliation: 'Reconciliation',
  tmc: 'TMC',
  platform: 'Platform',
  core: 'Core',
  lodging: 'Lodging',
};

/** Bento grid column spans per stage (6-column grid). */
const BENTO_SPAN: Readonly<Record<string, string>> = {
  search: 'span-3',
  pricing: 'span-3',
  booking: 'span-4',
  ticketing: 'span-2',
  exchange: 'span-2',
  settlement: 'span-2',
  reconciliation: 'span-2',
  reference: 'span-2',
  tmc: 'span-2',
  core: 'span-2',
  lodging: 'span-3',
  platform: 'span-3',
};

function repoRoot(): string {
  let cur = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(cur, 'pnpm-workspace.yaml'))) return cur;
    const parent = dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return resolve(dirname(fileURLToPath(import.meta.url)), '..');
}

function compareAgentIds(a: string, b: string): number {
  const [aMajor = 0, aMinor = 0] = a.split('.').map(Number);
  const [bMajor = 0, bMinor = 0] = b.split('.').map(Number);
  return aMajor - bMajor || aMinor - bMinor || a.localeCompare(b);
}

function stageSortKey(stage: string): number {
  const idx = (STAGE_ORDER as readonly string[]).indexOf(stage);
  return idx === -1 ? 1000 : idx;
}

function stageDisplay(stage: string): string {
  return STAGE_DISPLAY[stage] ?? stage.charAt(0).toUpperCase() + stage.slice(1);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function plural(n: number, word: string): string {
  return `${n} ${word}${n === 1 ? '' : 's'}`;
}

function groupByStage(nodes: readonly AgentGraphNode[]): Array<[string, AgentGraphNode[]]> {
  const map = new Map<string, AgentGraphNode[]>();
  for (const n of nodes) {
    const list = map.get(n.stage) ?? [];
    list.push(n);
    map.set(n.stage, list);
  }
  for (const list of map.values()) {
    list.sort((a, b) => compareAgentIds(a.id, b.id));
  }
  return [...map.entries()].sort(([a], [b]) => stageSortKey(a) - stageSortKey(b) || a.localeCompare(b));
}

interface WorkflowSequence {
  readonly label: string;
  readonly ids: readonly string[];
}

/** Reconstruct the ordered agent path of each workflow from its edges. */
function workflowSequences(graph: AgentGraph): WorkflowSequence[] {
  const byLabel = new Map<string, Array<{ source: string; target: string }>>();
  for (const e of graph.edges) {
    if (e.kind !== 'workflow') continue;
    const list = byLabel.get(e.label) ?? [];
    list.push({ source: e.source, target: e.target });
    byLabel.set(e.label, list);
  }
  const out: WorkflowSequence[] = [];
  for (const [label, edges] of byLabel) {
    const targets = new Set(edges.map((e) => e.target));
    const start = edges.map((e) => e.source).find((s) => !targets.has(s));
    const next = new Map(edges.map((e) => [e.source, e.target]));
    const ids: string[] = [];
    let cur: string | undefined = start ?? edges[0]?.source;
    while (cur !== undefined && ids.length <= edges.length) {
      ids.push(cur);
      cur = next.get(cur);
    }
    for (const e of edges) {
      if (!ids.includes(e.source)) ids.push(e.source);
      if (!ids.includes(e.target)) ids.push(e.target);
    }
    out.push({ label, ids });
  }
  out.sort((a, b) =>
    a.label === 'full_booking' ? -1 : b.label === 'full_booking' ? 1 : a.label.localeCompare(b.label),
  );
  return out;
}

export function renderAgentMapHtml(graph: AgentGraph): string {
  const stages = groupByStage(graph.nodes);
  const nodeById = new Map(graph.nodes.map((n) => [n.id, n]));
  const workflows = workflowSequences(graph);

  const segsHtml = workflows
    .map((wf, i) => {
      const featured = wf.label === 'full_booking';
      const active = i === 0;
      return `          <button type="button" class="seg${featured ? ' featured' : ''}${active ? ' active' : ''}" data-wf-select="${escapeHtml(wf.label)}" aria-pressed="${active}">
            <span class="seg-name">${escapeHtml(wf.label)}</span>
            <span class="seg-count">${plural(wf.ids.length, 'agent')}</span>
          </button>`;
    })
    .join('\n');

  const stagePathsHtml = workflows
    .map((wf, i) => {
      const active = i === 0;
      const parts: string[] = [];
      const stageSeq: string[] = [];
      wf.ids.forEach((id, idx) => {
        const n = nodeById.get(id);
        if (!n) return;
        if (!stageSeq.includes(n.stage)) stageSeq.push(n.stage);
        if (parts.length > 0) {
          parts.push(
            `<span class="conn" style="--i:${idx - 1}" aria-hidden="true"><span class="pulse"></span></span>`,
          );
        }
        const stub = n.contract_status === 'stub';
        parts.push(
          `<button type="button" class="cell" data-agent="${escapeHtml(id)}" style="--i:${idx}">
              <span class="cell-head"><span class="cell-stage">${escapeHtml(stageDisplay(n.stage))}</span><span class="cell-dot${stub ? ' stub' : ''}" aria-hidden="true"></span></span>
              <span class="cell-id">${escapeHtml(id)}</span>
              <span class="cell-name">${escapeHtml(n.name)}</span>
              <span class="cell-num" aria-hidden="true">${String(idx + 1).padStart(2, '0')}</span>
            </button>`,
        );
      });
      const stageFlow = stageSeq.map((s) => stageDisplay(s)).join(' → ');
      return `          <section class="stage-path${active ? ' active' : ''}" data-wf-path="${escapeHtml(wf.label)}"${active ? '' : ' hidden'} aria-label="${escapeHtml(wf.label)} pipeline">
            <div class="stage-meta">
              <div class="stage-meta-l">
                <span class="stage-wf-name">${escapeHtml(wf.label)}</span>
                <span class="stage-wf-tag">Orchestrator pipeline</span>
              </div>
              <div class="stage-wf-stats">${plural(wf.ids.length, 'agent')} · ${plural(stageSeq.length, 'stage')} · ${escapeHtml(stageFlow)}</div>
            </div>
            <div class="stage-track">
              ${parts.join('\n              ')}
            </div>
          </section>`;
    })
    .join('\n');

  const tilesHtml = stages
    .map(([stage, agents], i) => {
      const span = BENTO_SPAN[stage] ?? 'span-3';
      const preview =
        agents
          .slice(0, 2)
          .map((a) => a.name)
          .join(' · ') + (agents.length > 2 ? ` · +${agents.length - 2}` : '');
      const rows = agents
        .map((a) => {
          const stub = a.contract_status === 'stub';
          return `              <li><button type="button" class="agent-row" data-agent="${escapeHtml(a.id)}">
                <span class="a-dot${stub ? ' stub' : ''}" aria-hidden="true"></span>
                <span class="a-id">${escapeHtml(a.id)}</span>
                <span class="a-name">${escapeHtml(a.name)}</span>
                <span class="a-status">${a.contract_status}</span>
              </button></li>`;
        })
        .join('\n');
      return `        <section class="tile ${span}" id="tile-${escapeHtml(stage)}" data-stage="${escapeHtml(stage)}" data-reveal style="--i:${i % 3}">
          <button type="button" class="tile-head" aria-expanded="false">
            <span class="tile-top">
              <span class="tile-stage">${escapeHtml(stageDisplay(stage))}</span>
              <span class="tile-chevron" aria-hidden="true"></span>
            </span>
            <span class="tile-count">${agents.length}<em>${agents.length === 1 ? 'agent' : 'agents'}</em></span>
            <span class="tile-preview">${escapeHtml(preview)}</span>
            <span class="tile-path" aria-hidden="true"></span>
            <span class="tile-match" aria-live="polite"></span>
            <span class="tile-wm" aria-hidden="true">${String(i + 1).padStart(2, '0')}</span>
          </button>
          <div class="tile-body">
            <ul class="agent-list">
${rows}
            </ul>
          </div>
        </section>`;
    })
    .join('\n');

  const payload = JSON.stringify(graph);
  const stageNamesJson = JSON.stringify(STAGE_DISPLAY);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Telivity Otaip · Agent connections</title>
  <meta name="description" content="Interactive map of the Telivity Otaip agent system — ${graph.total_nodes} typed travel agents and the orchestrator pipelines that connect them." />
  <link rel="icon" href="assets/telivity/favicon.ico" sizes="any" />
  <link rel="icon" href="assets/telivity/favicon.svg" type="image/svg+xml" />
  <meta property="og:image" content="assets/telivity/og-image.png" />
  <script>document.documentElement.classList.add('js');</script>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap" rel="stylesheet" />
  <noscript><style>[data-reveal] { opacity: 1 !important; transform: none !important; }</style></noscript>
  <style>
    :root {
      /* Telivity brand — from telivity.app */
      --teal: #06bdb4;
      --teal-dark: #00a692;
      --teal-light: #2cd1b9;
      --navy: #23273d;
      --slate: #444863;
      --mid: #bbbbc4;
      --fog: #f0f0f6;
      --ink-1: var(--navy);
      --ink-2: var(--slate);
      --ink-3: #7a7e96;
      --ink-4: #9aa0b4;
      --hairline: rgba(35, 39, 61, 0.09);
      --hairline-strong: rgba(35, 39, 61, 0.16);
      --hairline-mid: rgba(187, 187, 196, 0.38);
      --shadow-soft:
        0 1px 2px rgba(35, 39, 61, 0.05),
        0 10px 28px -10px rgba(35, 39, 61, 0.1),
        0 32px 64px -24px rgba(35, 39, 61, 0.12);
      --shadow-lift:
        0 2px 6px rgba(35, 39, 61, 0.06),
        0 18px 40px -14px rgba(35, 39, 61, 0.16),
        0 48px 96px -32px rgba(35, 39, 61, 0.18);
      --font: "Montserrat", system-ui, sans-serif;
      --mono: ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace;
      --spring: cubic-bezier(0.34, 1.3, 0.64, 1);
      --ease-out: cubic-bezier(0.22, 1, 0.36, 1);
    }
    * { box-sizing: border-box; }
    html { scroll-behavior: smooth; }
    html, body { margin: 0; min-height: 100%; }
    body {
      font-family: var(--font);
      color: var(--ink-1);
      background:
        radial-gradient(1200px 700px at 85% -10%, rgba(6, 189, 180, 0.06), transparent 60%),
        radial-gradient(900px 600px at -10% 30%, rgba(44, 209, 185, 0.05), transparent 55%),
        var(--fog);
      -webkit-font-smoothing: antialiased;
      text-rendering: optimizeLegibility;
    }
    body::after {
      content: "";
      position: fixed;
      inset: 0;
      z-index: 200;
      pointer-events: none;
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='180' height='180' filter='url(%23n)'/%3E%3C/svg%3E");
      opacity: 0.045;
      mix-blend-mode: multiply;
    }
    ::selection { background: rgba(6, 189, 180, 0.25); }
    a { color: var(--teal-dark); }
    :focus-visible { outline: 2px solid var(--teal); outline-offset: 2px; border-radius: 4px; }

    .shell { max-width: 74rem; margin: 0 auto; padding: 0 1.5rem; }

    /* ---------- Nav ---------- */
    .nav {
      position: sticky;
      top: 0;
      z-index: 100;
      backdrop-filter: blur(16px);
      -webkit-backdrop-filter: blur(16px);
      background: rgba(240, 240, 246, 0.65);
      transition: background 0.3s ease, box-shadow 0.3s ease;
    }
    .nav.scrolled {
      background: rgba(240, 240, 246, 0.88);
      box-shadow: 0 1px 0 var(--hairline);
    }
    .nav-inner {
      max-width: 74rem;
      margin: 0 auto;
      padding: 0.75rem 1.5rem;
      display: flex;
      align-items: center;
      gap: 2rem;
    }
    .brand {
      display: inline-flex;
      align-items: baseline;
      gap: 0.5rem;
      text-decoration: none;
      color: var(--navy);
    }
    .brand img { width: 22px; height: 22px; display: block; align-self: center; }
    .brand-name { font-weight: 700; font-size: 1.05rem; letter-spacing: -0.02em; }
    .brand-sub { font-weight: 400; font-size: 0.92rem; color: var(--ink-4); }
    .nav-links { margin-left: auto; display: flex; gap: 1.7rem; align-items: center; }
    .nav-links a {
      color: var(--slate);
      text-decoration: none;
      font-size: 0.82rem;
      font-weight: 500;
      transition: color 0.15s ease;
    }
    .nav-links a:hover { color: var(--teal-dark); }
    .nav-links a.ext { color: var(--ink-4); }
    @media (max-width: 640px) {
      .nav-links { gap: 1rem; }
      .nav-links a.ext { display: none; }
    }

    /* ---------- Connection stage (first viewport) ---------- */
    .stage-view {
      min-height: calc(100svh - 3.5rem);
      display: flex;
      flex-direction: column;
      padding: 3.2rem 0 3.6rem;
    }
    .stage-view .shell {
      flex: 1;
      width: 100%;
      display: flex;
      flex-direction: column;
    }
    .eyebrow {
      margin: 0 0 1.1rem;
      font-size: 0.72rem;
      font-weight: 600;
      letter-spacing: 0.26em;
      text-transform: uppercase;
      color: var(--teal-dark);
    }
    h1 {
      margin: 0;
      font-weight: 700;
      font-size: clamp(2.7rem, 5.6vw, 4.4rem);
      letter-spacing: -0.045em;
      line-height: 1.02;
      color: var(--navy);
    }
    h1 .t { color: var(--teal); }
    .fact {
      margin: 1.15rem 0 0;
      max-width: 46rem;
      font-size: clamp(0.98rem, 1.4vw, 1.12rem);
      font-weight: 300;
      line-height: 1.6;
      color: var(--ink-2);
    }
    .fact code { font-family: var(--mono); font-size: 0.82em; color: var(--teal-dark); }

    /* Workflow selector — bento segments */
    .wf-select {
      display: flex;
      flex-wrap: wrap;
      gap: 0.45rem;
      width: fit-content;
      max-width: 100%;
      margin: 2.1rem 0 1.25rem;
      padding: 0.4rem;
      background: rgba(255, 255, 255, 0.62);
      border: 1px solid var(--hairline-mid);
      border-radius: 18px;
    }
    .seg {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      gap: 0.2rem;
      padding: 0.55rem 1.05rem 0.6rem;
      border: 0;
      border-radius: 13px;
      background: transparent;
      font: inherit;
      color: var(--ink-3);
      cursor: pointer;
      transition: background 0.2s ease, color 0.2s ease, box-shadow 0.25s ease;
    }
    .seg:hover { background: rgba(6, 189, 180, 0.08); color: var(--ink-1); }
    .seg.active {
      background: var(--navy);
      color: #fff;
      box-shadow: 0 8px 18px -8px rgba(35, 39, 61, 0.5);
    }
    .seg-name {
      display: inline-flex;
      align-items: center;
      gap: 0.45rem;
      font-family: var(--mono);
      font-size: 0.8rem;
      font-weight: 600;
      letter-spacing: -0.01em;
    }
    .seg.featured .seg-name::before {
      content: "";
      width: 6px;
      height: 6px;
      border-radius: 50%;
      background: var(--teal);
    }
    .seg-count { font-size: 0.64rem; font-weight: 400; color: var(--ink-4); }
    .seg.active .seg-count { color: rgba(255, 255, 255, 0.62); }
    .seg.featured .seg-count { padding-left: 0.83rem; }

    /* The stage card */
    .stage-card {
      flex: 1;
      min-height: 22rem;
      display: flex;
      flex-direction: column;
      background:
        radial-gradient(640px 220px at 18% 0%, rgba(6, 189, 180, 0.05), transparent 62%),
        #fff;
      border: 1px solid var(--hairline-mid);
      border-radius: 28px;
      box-shadow: var(--shadow-soft);
      overflow: hidden;
      transition: box-shadow 0.45s ease;
    }
    .stage-card.flash { box-shadow: 0 0 0 3px rgba(6, 189, 180, 0.35), var(--shadow-lift); }
    .stage-paths {
      position: relative;
      flex: 1;
      display: flex;
      flex-direction: column;
      min-height: 0;
    }
    .stage-path {
      flex: 1;
      display: flex;
      flex-direction: column;
      min-height: 0;
      transition: opacity 0.24s ease;
    }
    .stage-path[hidden] { display: none; }
    .stage-path.leaving {
      position: absolute;
      inset: 0;
      opacity: 0;
      pointer-events: none;
    }
    .stage-meta {
      display: flex;
      align-items: baseline;
      justify-content: space-between;
      flex-wrap: wrap;
      gap: 0.4rem 1.25rem;
      padding: 1.5rem 2rem 0;
    }
    .stage-wf-name {
      font-family: var(--mono);
      font-size: 1.02rem;
      font-weight: 600;
      color: var(--navy);
    }
    .stage-wf-name::before {
      content: "";
      display: inline-block;
      width: 8px;
      height: 8px;
      border-radius: 2px;
      margin-right: 0.55rem;
      background: var(--teal);
    }
    .stage-wf-tag {
      margin-left: 0.85rem;
      font-size: 0.64rem;
      font-weight: 600;
      letter-spacing: 0.17em;
      text-transform: uppercase;
      color: var(--ink-4);
    }
    .stage-wf-stats { font-size: 0.76rem; font-weight: 300; color: var(--ink-3); }

    .stage-track {
      flex: 1;
      display: flex;
      align-items: center;
      overflow-x: auto;
      overflow-y: hidden;
      overscroll-behavior-x: contain;
      padding: 1.5rem 2rem 1.3rem;
      scrollbar-width: thin;
      scrollbar-color: rgba(6, 189, 180, 0.35) transparent;
      -webkit-mask-image: linear-gradient(90deg, transparent, #000 2.4rem, #000 calc(100% - 2.4rem), transparent);
      mask-image: linear-gradient(90deg, transparent, #000 2.4rem, #000 calc(100% - 2.4rem), transparent);
    }
    .stage-track::-webkit-scrollbar { height: 6px; }
    .stage-track::-webkit-scrollbar-thumb { background: rgba(6, 189, 180, 0.3); border-radius: 3px; }
    .stage-track::-webkit-scrollbar-track { background: transparent; }
    .stage-track::before,
    .stage-track::after { content: ""; margin: auto; }
    .stage-track.dragging { cursor: grabbing; }
    .stage-track.dragging .cell { cursor: grabbing; }

    /* Agent cells */
    .cell {
      position: relative;
      flex: none;
      width: 10.9rem;
      min-height: 8.6rem;
      display: flex;
      flex-direction: column;
      gap: 0.45rem;
      padding: 1rem 1.05rem 0.95rem;
      background: #fff;
      border: 1px solid var(--hairline-mid);
      border-radius: 20px;
      box-shadow: 0 1px 2px rgba(35, 39, 61, 0.04), 0 12px 28px -14px rgba(35, 39, 61, 0.12);
      font: inherit;
      text-align: left;
      color: inherit;
      cursor: pointer;
      transition: border-color 0.25s ease, box-shadow 0.3s ease, background 0.25s ease;
    }
    .cell:hover {
      border-color: rgba(6, 189, 180, 0.55);
      box-shadow: 0 2px 4px rgba(35, 39, 61, 0.05), 0 20px 42px -16px rgba(6, 189, 180, 0.42);
    }
    .cell-head { display: flex; align-items: center; justify-content: space-between; gap: 0.5rem; }
    .cell-stage {
      font-size: 0.6rem;
      font-weight: 600;
      letter-spacing: 0.15em;
      text-transform: uppercase;
      color: var(--teal-dark);
    }
    .cell-dot { flex: none; width: 7px; height: 7px; border-radius: 50%; background: var(--teal); }
    .cell-dot.stub { background: transparent; border: 1.5px dashed var(--mid); }
    .cell-id {
      margin-top: 0.4rem;
      font-family: var(--mono);
      font-size: 1.5rem;
      font-weight: 600;
      letter-spacing: -0.03em;
      line-height: 1;
      color: var(--navy);
    }
    .cell-name { font-size: 0.8rem; font-weight: 500; line-height: 1.4; color: var(--ink-2); }
    .cell-num {
      position: absolute;
      right: 0.85rem;
      bottom: 0.4rem;
      font-size: 2rem;
      font-weight: 700;
      letter-spacing: -0.04em;
      line-height: 1;
      color: rgba(35, 39, 61, 0.05);
      pointer-events: none;
      user-select: none;
    }
    .cell.sel {
      border-color: var(--teal);
      box-shadow: 0 0 0 3px rgba(6, 189, 180, 0.25), 0 18px 40px -16px rgba(6, 189, 180, 0.45);
    }
    .cell.nb { background: #f1faf8; border-color: rgba(6, 189, 180, 0.4); }
    .cell.dep { border-style: dashed; border-color: rgba(6, 189, 180, 0.65); }

    /* Connector bars — the drama */
    .conn {
      position: relative;
      flex: none;
      width: 3.15rem;
      height: 12px;
      transform-origin: left center;
    }
    .conn::before {
      content: "";
      position: absolute;
      left: 1px;
      right: 8px;
      top: 50%;
      height: 2px;
      transform: translateY(-50%);
      border-radius: 2px;
      background: rgba(35, 39, 61, 0.14);
      transition: background 0.25s ease;
    }
    .conn::after {
      content: "";
      position: absolute;
      right: 1px;
      top: 50%;
      width: 7px;
      height: 7px;
      border-top: 1.5px solid rgba(0, 166, 146, 0.75);
      border-right: 1.5px solid rgba(0, 166, 146, 0.75);
      transform: translateY(-50%) rotate(45deg);
      transition: border-color 0.25s ease;
    }
    .conn .pulse {
      position: absolute;
      left: 0;
      top: 50%;
      width: 34%;
      height: 2px;
      border-radius: 2px;
      background: linear-gradient(90deg, transparent, var(--teal) 42%, var(--teal-light) 58%, transparent);
      transform: translateY(-50%);
      animation: pulse-x 2.2s cubic-bezier(0.42, 0, 0.3, 1) infinite;
      animation-delay: calc(var(--i, 0) * 0.3s);
    }
    @keyframes pulse-x {
      0% { transform: translate(-120%, -50%); opacity: 0; }
      16% { opacity: 1; }
      84% { opacity: 1; }
      100% { transform: translate(330%, -50%); opacity: 0; }
    }
    .conn.lit::before { background: rgba(6, 189, 180, 0.6); }
    .conn.lit::after { border-color: var(--teal-dark); }

    /* Entrance — only when JS is on (html.js), so no-JS still shows the stage */
    .js .stage-path .cell,
    .js .stage-path .conn { opacity: 0; }
    .js .stage-path.in .cell {
      animation: cell-in 0.68s var(--spring) both;
      animation-delay: calc(var(--i, 0) * 65ms);
    }
    .js .stage-path.in .conn {
      animation: conn-in 0.55s var(--ease-out) both;
      animation-delay: calc(var(--i, 0) * 65ms + 150ms);
    }
    @keyframes cell-in {
      from { opacity: 0; transform: translateY(18px) scale(0.985); }
      to { opacity: 1; transform: none; }
    }
    @keyframes conn-in {
      from { opacity: 0; transform: scaleX(0.25); }
      to { opacity: 1; transform: scaleX(1); }
    }

    .stage-legend {
      display: flex;
      align-items: center;
      gap: 1.15rem;
      padding: 0.8rem 2rem 0.95rem;
      border-top: 1px solid var(--hairline);
      font-size: 0.68rem;
      font-weight: 300;
      color: var(--ink-4);
    }
    .stage-legend .lg { display: inline-flex; align-items: center; gap: 0.4rem; }
    .lg-dot { display: inline-block; width: 7px; height: 7px; border-radius: 50%; background: var(--teal); }
    .lg-dot.stub { background: transparent; border: 1.5px dashed var(--mid); }
    .lg-hint { margin-left: auto; }
    @media (max-width: 720px) { .lg-hint { display: none; } }

    /* ---------- Sections ---------- */
    .section { padding: 6.5rem 0; border-top: 1px solid var(--hairline); scroll-margin-top: 3.5rem; }
    .s-head { max-width: 46rem; margin-bottom: 2.6rem; }
    .s-head h2 {
      margin: 0;
      font-size: clamp(2.2rem, 4.6vw, 3.4rem);
      font-weight: 700;
      letter-spacing: -0.04em;
      line-height: 1.04;
      color: var(--navy);
    }
    .s-head .sub {
      margin: 1.05rem 0 0;
      font-size: 1.02rem;
      font-weight: 300;
      line-height: 1.55;
      color: var(--ink-3);
    }

    [data-reveal] {
      opacity: 0;
      transform: translateY(26px);
      transition: opacity 0.7s ease, transform 0.85s var(--spring);
      transition-delay: calc(var(--i, 0) * 70ms);
    }
    [data-reveal].in { opacity: 1; transform: none; }

    /* ---------- Quiet controls ---------- */
    .controls {
      display: flex;
      flex-wrap: wrap;
      gap: 0.55rem;
      align-items: center;
      margin-bottom: 1.5rem;
    }
    .controls input, .controls select {
      border: 1px solid var(--hairline);
      background: rgba(255, 255, 255, 0.7);
      color: var(--ink-1);
      border-radius: 11px;
      padding: 0.5rem 0.85rem;
      font: inherit;
      font-size: 0.8rem;
      transition: border-color 0.15s ease, box-shadow 0.15s ease, background 0.15s ease;
    }
    .controls input { min-width: 12rem; }
    .controls input::placeholder { color: var(--ink-4); }
    .controls input:focus, .controls select:focus {
      outline: none;
      border-color: var(--teal);
      background: #fff;
      box-shadow: 0 0 0 3px rgba(6, 189, 180, 0.16);
    }

    /* ---------- Bento ---------- */
    .bento {
      display: grid;
      grid-template-columns: repeat(6, 1fr);
      gap: 1.1rem;
    }
    .span-2 { grid-column: span 2; }
    .span-3 { grid-column: span 3; }
    .span-4 { grid-column: span 4; }
    @media (max-width: 1080px) {
      .bento { grid-template-columns: repeat(2, 1fr); }
      .span-2 { grid-column: span 1; }
      .span-3, .span-4 { grid-column: span 2; }
    }
    @media (max-width: 620px) {
      .bento { grid-template-columns: 1fr; }
      .span-2, .span-3, .span-4 { grid-column: span 1; }
    }

    .tile {
      position: relative;
      background: #fff;
      border: 1px solid var(--hairline-mid);
      border-radius: 24px;
      box-shadow: var(--shadow-soft);
      overflow: hidden;
      display: flex;
      flex-direction: column;
      transition: box-shadow 0.35s ease, transform 0.35s var(--ease-out), border-color 0.3s ease;
    }
    .tile:hover { box-shadow: var(--shadow-lift); transform: translateY(-3px); }
    .tile.open { border-color: rgba(6, 189, 180, 0.45); }
    .tile-head {
      position: relative;
      display: block;
      width: 100%;
      padding: 1.8rem 1.8rem 1.65rem;
      background: none;
      border: 0;
      font: inherit;
      color: inherit;
      text-align: left;
      cursor: pointer;
    }
    .tile-wm {
      position: absolute;
      right: 1.15rem;
      bottom: 0.35rem;
      font-size: 5.6rem;
      font-weight: 700;
      letter-spacing: -0.05em;
      line-height: 1;
      color: rgba(35, 39, 61, 0.05);
      pointer-events: none;
      user-select: none;
    }
    .tile-top { display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; }
    .tile-stage {
      font-size: 0.72rem;
      font-weight: 600;
      letter-spacing: 0.18em;
      text-transform: uppercase;
      color: var(--teal-dark);
    }
    .tile-chevron {
      flex: none;
      width: 26px;
      height: 26px;
      border-radius: 50%;
      border: 1px solid var(--hairline-strong);
      display: grid;
      place-items: center;
      transition: transform 0.4s var(--spring), background 0.2s ease, border-color 0.2s ease;
    }
    .tile-chevron::before {
      content: "";
      width: 7px;
      height: 7px;
      border-right: 1.5px solid var(--slate);
      border-bottom: 1.5px solid var(--slate);
      transform: rotate(45deg) translate(-1px, -1px);
    }
    .tile.open .tile-chevron {
      transform: rotate(180deg);
      background: rgba(6, 189, 180, 0.09);
      border-color: rgba(6, 189, 180, 0.45);
    }
    .tile-count {
      display: block;
      margin-top: 1rem;
      font-size: 2.6rem;
      font-weight: 700;
      letter-spacing: -0.045em;
      line-height: 1;
      color: var(--navy);
    }
    .tile-count em {
      font-style: normal;
      font-size: 0.85rem;
      font-weight: 400;
      letter-spacing: 0;
      color: var(--ink-3);
      margin-left: 0.35rem;
    }
    .tile-preview {
      display: block;
      margin-top: 0.75rem;
      font-size: 0.82rem;
      font-weight: 300;
      line-height: 1.55;
      color: var(--ink-3);
    }
    .tile-path {
      display: block;
      margin-top: 0.55rem;
      font-family: var(--mono);
      font-size: 0.66rem;
      letter-spacing: 0.06em;
      color: var(--teal-dark);
      min-height: 0.9rem;
    }
    .tile-match {
      display: block;
      margin-top: 0.2rem;
      font-family: var(--mono);
      font-size: 0.66rem;
      letter-spacing: 0.06em;
      color: var(--ink-4);
      min-height: 0.9rem;
    }
    .tile-body {
      max-height: 0;
      overflow: hidden;
      transition: max-height 0.55s var(--ease-out);
    }
    .tile.open .tile-body { max-height: 26rem; overflow-y: auto; }
    .agent-list {
      list-style: none;
      margin: 0 1rem 1rem;
      padding: 0.4rem 0 0.2rem;
      border-top: 1px solid var(--hairline);
      display: flex;
      flex-direction: column;
    }
    .agent-list li + li { border-top: 1px solid var(--hairline); }
    .agent-row {
      width: 100%;
      min-height: 2.9rem;
      display: flex;
      align-items: center;
      gap: 0.65rem;
      padding: 0.72rem 0.6rem;
      border: 0;
      background: none;
      border-radius: 8px;
      font: inherit;
      text-align: left;
      color: inherit;
      cursor: pointer;
      transition: background 0.15s ease, opacity 0.35s ease, outline-color 0.2s ease;
      outline: 1.5px solid transparent;
      outline-offset: -1.5px;
    }
    .agent-row:hover { background: rgba(6, 189, 180, 0.07); }
    .agent-row.dim { opacity: 0.34; }
    .agent-row.dim.sel, .agent-row.dim.nb, .agent-row.dim.dep { opacity: 1; }
    .agent-row.on-path .a-dot { box-shadow: 0 0 0 3px rgba(6, 189, 180, 0.16); }
    .agent-row.sel { background: rgba(6, 189, 180, 0.1); outline-color: rgba(6, 189, 180, 0.55); }
    .agent-row.nb { background: rgba(6, 189, 180, 0.06); }
    .agent-row.dep { outline-style: dashed; outline-color: rgba(6, 189, 180, 0.6); }
    .a-dot { flex: none; width: 7px; height: 7px; border-radius: 50%; background: var(--teal); }
    .a-dot.stub { background: transparent; border: 1.5px dashed var(--mid); }
    .a-id { flex: none; min-width: 2.1rem; font-family: var(--mono); font-size: 0.74rem; color: var(--teal-dark); }
    .a-name { flex: 1; font-size: 0.88rem; font-weight: 500; color: var(--ink-2); line-height: 1.35; }
    .a-status {
      flex: none;
      font-family: var(--mono);
      font-size: 0.6rem;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--ink-4);
    }

    /* ---------- Detail panel ---------- */
    .scrim {
      position: fixed;
      inset: 0;
      z-index: 240;
      background: rgba(35, 39, 61, 0.28);
      backdrop-filter: blur(3px);
      -webkit-backdrop-filter: blur(3px);
      opacity: 0;
      transition: opacity 0.3s ease;
    }
    .scrim.show { opacity: 1; }
    .panel {
      position: fixed;
      top: 0;
      right: 0;
      bottom: 0;
      z-index: 260;
      width: min(26rem, 94vw);
      background: #fff;
      border-left: 1px solid var(--hairline);
      box-shadow: -32px 0 90px -30px rgba(35, 39, 61, 0.35);
      transform: translateX(104%);
      transition: transform 0.55s var(--spring);
      overflow-y: auto;
    }
    .panel.open { transform: none; }
    .panel-inner { padding: 2.4rem 1.8rem 3rem; }
    .panel-close {
      position: absolute;
      top: 1rem;
      right: 1rem;
      width: 32px;
      height: 32px;
      border-radius: 50%;
      border: 1px solid var(--hairline-strong);
      background: #fff;
      color: var(--slate);
      font-size: 1.05rem;
      line-height: 1;
      cursor: pointer;
      transition: border-color 0.2s ease, color 0.2s ease, transform 0.3s var(--spring);
    }
    .panel-close:hover { border-color: var(--teal); color: var(--teal-dark); transform: rotate(90deg); }
    .p-id {
      font-family: var(--mono);
      font-size: 0.75rem;
      letter-spacing: 0.06em;
      color: var(--teal-dark);
      margin-bottom: 0.5rem;
    }
    .panel h3 {
      margin: 0 2rem 0.8rem 0;
      font-size: 1.45rem;
      font-weight: 700;
      letter-spacing: -0.025em;
      line-height: 1.15;
      color: var(--navy);
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 0.4rem;
      font-family: var(--mono);
      font-size: 0.64rem;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: var(--ink-3);
      margin-bottom: 1.4rem;
    }
    .badge i {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: var(--teal);
      box-shadow: 0 0 0 3px rgba(6, 189, 180, 0.18);
    }
    .badge.stub i { background: transparent; border: 1.5px dashed var(--mid); box-shadow: none; }
    .panel dl {
      margin: 0;
      display: grid;
      grid-template-columns: 4.6rem 1fr;
      gap: 0.5rem 0.75rem;
      font-size: 0.83rem;
      padding: 1.1rem 0;
      border-top: 1px solid var(--hairline);
      border-bottom: 1px solid var(--hairline);
    }
    .panel dt { color: var(--ink-4); font-weight: 400; }
    .panel dd { margin: 0; color: var(--ink-2); word-break: break-word; }
    .panel code { font-family: var(--mono); font-size: 0.7rem; color: var(--teal-dark); }
    .p-label {
      margin: 1.5rem 0 0.55rem;
      font-size: 0.68rem;
      font-weight: 600;
      letter-spacing: 0.16em;
      text-transform: uppercase;
      color: var(--ink-4);
    }
    .mini-pills { display: flex; flex-wrap: wrap; gap: 0.35rem; }
    .mini-pill {
      border: 1px solid rgba(6, 189, 180, 0.4);
      background: rgba(6, 189, 180, 0.06);
      color: var(--teal-dark);
      border-radius: 10px;
      padding: 0.34rem 0.75rem;
      font-family: var(--mono);
      font-size: 0.68rem;
      cursor: pointer;
      transition: background 0.15s ease, border-color 0.15s ease;
    }
    .mini-pill:hover { background: rgba(6, 189, 180, 0.14); border-color: var(--teal); }
    .p-dim { margin: 0; font-size: 0.8rem; font-weight: 300; color: var(--ink-4); }
    .conn-list { margin: 0; padding: 0; list-style: none; display: flex; flex-direction: column; gap: 0.4rem; }
    .conn-list li { font-family: var(--mono); font-size: 0.74rem; color: var(--ink-3); }
    .conn-list .dir { color: var(--teal); }
    .conn-list button {
      background: none;
      border: none;
      padding: 0;
      font: inherit;
      color: var(--teal-dark);
      cursor: pointer;
    }
    .conn-list button:hover { text-decoration: underline; }
    .conn-list .c-kind { color: var(--ink-4); }
    .dep-row { display: flex; flex-direction: column; gap: 0.25rem; margin-bottom: 0.55rem; }
    .dep-pill {
      align-self: flex-start;
      border: 1.5px dashed rgba(6, 189, 180, 0.55);
      background: rgba(6, 189, 180, 0.04);
      color: var(--teal-dark);
      border-radius: 10px;
      padding: 0.38rem 0.8rem;
      font-family: var(--mono);
      font-size: 0.68rem;
      cursor: pointer;
      transition: background 0.15s ease, border-color 0.15s ease;
    }
    .dep-pill:hover { background: rgba(6, 189, 180, 0.12); border-color: var(--teal); }
    .dep-pill .dep-arrow { color: var(--teal); }
    .dep-label { font-family: var(--mono); font-size: 0.6rem; color: var(--ink-4); padding-left: 0.15rem; }

    /* ---------- Footer ---------- */
    footer {
      border-top: 1px solid var(--hairline);
      padding: 2.4rem 0 3.2rem;
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 0.6rem 1.5rem;
      justify-content: space-between;
      font-size: 0.78rem;
      font-weight: 300;
      color: var(--ink-3);
    }
    footer .brand img { width: 18px; height: 18px; }
    footer .brand-name { font-size: 0.92rem; }
    footer .gen { font-family: var(--mono); font-size: 0.66rem; color: var(--ink-4); }
    footer code { font-family: var(--mono); }

    @media (max-width: 860px) {
      .stage-view { padding-top: 2.4rem; }
      .stage-meta { padding: 1.25rem 1.4rem 0; }
      .stage-track { padding: 1.25rem 1.4rem 1.1rem; }
      .stage-legend { padding: 0.75rem 1.4rem 0.9rem; }
      .cell { width: 9.6rem; min-height: 8rem; }
      .conn { width: 2.4rem; }
    }

    @media (prefers-reduced-motion: reduce) {
      html { scroll-behavior: auto; }
      *, *::before, *::after {
        animation: none !important;
        transition: none !important;
      }
      [data-reveal] { opacity: 1; transform: none; }
      .js .stage-path .cell, .js .stage-path .conn { opacity: 1; }
      .conn .pulse { display: none; }
    }
  </style>
</head>
<body>
  <nav class="nav" id="nav">
    <div class="nav-inner">
      <a class="brand" href="#stage" aria-label="Telivity Otaip agent graph">
        <img src="assets/telivity/logo-1color.svg" width="22" height="22" alt="" />
        <span class="brand-name">Telivity</span>
        <span class="brand-sub">/ Otaip</span>
      </a>
      <div class="nav-links">
        <a href="#stage">Stage</a>
        <a href="#agents">Agents</a>
        <a class="ext" href="https://telivity.app">telivity.app ↗</a>
      </div>
    </div>
  </nav>

  <header class="stage-view" id="stage">
    <div class="shell">
      <div class="stage-head">
        <p class="eyebrow" data-reveal style="--i:0">Telivity Otaip · Agent graph</p>
        <h1 data-reveal style="--i:1">Agent connections<span class="t">.</span></h1>
        <p class="fact" data-reveal style="--i:2">${graph.total_nodes} agents · ${stages.length} stages · ${workflows.length} orchestrator pipelines — one shared contract, rendered from <code>agents.graph.json</code>.</p>
      </div>
      <div class="wf-select" role="group" aria-label="Select workflow" data-reveal style="--i:3">
${segsHtml}
      </div>
      <div class="stage-card" id="stage-card" data-reveal style="--i:4">
        <div class="stage-paths">
${stagePathsHtml}
        </div>
        <div class="stage-legend">
          <span class="lg"><i class="lg-dot"></i>active</span>
          <span class="lg"><i class="lg-dot stub"></i>stub</span>
          <span class="lg-hint">scroll or drag the track · select a cell for detail</span>
        </div>
      </div>
    </div>
  </header>

  <section class="section" id="agents">
    <div class="shell">
      <div class="s-head" data-reveal>
        <p class="eyebrow">The system</p>
        <h2>Every agent, by stage.</h2>
        <p class="sub">Agents on the selected pipeline stay lit — the rest dim. Open a stage, select an agent, follow its connections.</p>
      </div>
      <div class="controls" data-reveal>
        <input id="search" type="search" placeholder="Search agents…" aria-label="Search agents" />
        <select id="stage-filter" aria-label="Filter by stage">
          <option value="all">All stages</option>
        </select>
        <select id="status-filter" aria-label="Filter by status">
          <option value="all">All status</option>
          <option value="active">Active</option>
          <option value="stub">Stub</option>
        </select>
      </div>
      <div class="bento" id="bento">
${tilesHtml}
      </div>
    </div>
  </section>

  <div class="shell">
    <footer>
      <a class="brand" href="https://telivity.app">
        <img src="assets/telivity/logo-1color.svg" width="18" height="18" alt="" />
        <span class="brand-name">Telivity</span>
      </a>
      <span>Otaip agent graph · ${graph.total_nodes} agents · ${stages.length} stages · ${workflows.length} workflows</span>
      <span class="gen">generated from <code>agents.graph.json</code> · <code>pnpm gen:agent-map</code></span>
    </footer>
  </div>

  <div class="scrim" id="scrim" hidden></div>
  <aside class="panel" id="panel" aria-hidden="true" aria-label="Agent detail">
    <button type="button" class="panel-close" id="panel-close" aria-label="Close">×</button>
    <div class="panel-inner" id="panel-content"></div>
  </aside>

  <script id="graph-data" type="application/json">${payload.replace(/</g, '\\u003c')}</script>
  <script>
    const graph = JSON.parse(document.getElementById('graph-data').textContent);
    const STAGE_NAMES = ${stageNamesJson};
    const nodesById = {};
    for (const n of graph.nodes) nodesById[n.id] = n;

    const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    const revealEls = Array.from(document.querySelectorAll('[data-reveal]'));
    function revealInViewport() {
      const vh = window.innerHeight || document.documentElement.clientHeight;
      for (const el of revealEls) {
        if (el.classList.contains('in')) continue;
        const r = el.getBoundingClientRect();
        if (r.top < vh * 0.94 && r.bottom > 0) el.classList.add('in');
      }
    }
    if (reduceMotion || !('IntersectionObserver' in window)) {
      for (const el of revealEls) el.classList.add('in');
    } else {
      const io = new IntersectionObserver((entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            entry.target.classList.add('in');
            io.unobserve(entry.target);
          }
        }
      }, { threshold: 0.1, rootMargin: '0px 0px -6% 0px' });
      for (const el of revealEls) io.observe(el);
      revealInViewport();
    }

    const nav = document.getElementById('nav');
    const onScroll = () => { nav.classList.toggle('scrolled', window.scrollY > 10); };
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();

    function escape(s) {
      return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }

    for (const head of document.querySelectorAll('.tile-head')) {
      head.addEventListener('click', () => {
        const tile = head.closest('.tile');
        const open = tile.classList.toggle('open');
        head.setAttribute('aria-expanded', open ? 'true' : 'false');
      });
    }

    /* ---------- Connection stage ---------- */
    const segs = Array.from(document.querySelectorAll('[data-wf-select]'));
    const stagePaths = Array.from(document.querySelectorAll('.stage-path'));
    const stageCard = document.getElementById('stage-card');
    const pathCache = {};
    let selectedAgent = null;

    function pathMembers(label) {
      let set = pathCache[label];
      if (!set) {
        set = new Set();
        for (const e of graph.edges) {
          if (e.kind === 'workflow' && e.label === label) {
            set.add(e.source);
            set.add(e.target);
          }
        }
        pathCache[label] = set;
      }
      return set;
    }

    const firstSeg = document.querySelector('.seg.active') || segs[0];
    let activeWf = firstSeg ? firstSeg.dataset.wfSelect : null;

    function applyPathHighlight() {
      if (!activeWf) return;
      const members = pathMembers(activeWf);
      for (const tile of document.querySelectorAll('.tile')) {
        let onPath = 0;
        for (const row of tile.querySelectorAll('.agent-row')) {
          const on = members.has(row.dataset.agent);
          row.classList.toggle('on-path', on);
          row.classList.toggle('dim', !on);
          if (on) onPath++;
        }
        const note = tile.querySelector('.tile-path');
        if (note) note.textContent = onPath ? onPath + ' on path' : '';
      }
    }

    function showPath(label) {
      let next = null;
      for (const p of stagePaths) {
        if (p.dataset.wfPath === label) { next = p; break; }
      }
      if (!next) return;
      const current = document.querySelector('.stage-path.active');
      if (current === next) return;
      if (current) {
        if (reduceMotion) {
          current.classList.remove('active', 'in');
          current.hidden = true;
        } else {
          current.classList.add('leaving');
          setTimeout(() => {
            current.classList.remove('active', 'leaving', 'in');
            current.hidden = true;
          }, 240);
        }
      }
      next.hidden = false;
      next.classList.add('active');
      if (reduceMotion) {
        next.classList.add('in');
      } else {
        requestAnimationFrame(() => requestAnimationFrame(() => next.classList.add('in')));
      }
    }

    function setWorkflow(label) {
      if (!label || label === activeWf) return;
      activeWf = label;
      for (const seg of segs) {
        const on = seg.dataset.wfSelect === label;
        seg.classList.toggle('active', on);
        seg.setAttribute('aria-pressed', on ? 'true' : 'false');
      }
      showPath(label);
      applyPathHighlight();
      if (selectedAgent) highlightSelection(selectedAgent);
    }

    for (const seg of segs) {
      seg.addEventListener('click', () => setWorkflow(seg.dataset.wfSelect));
    }

    /* Track: wheel mapping + drag to scroll */
    for (const track of document.querySelectorAll('.stage-track')) {
      track.addEventListener('wheel', (e) => {
        if (track.scrollWidth <= track.clientWidth) return;
        if (Math.abs(e.deltaY) > Math.abs(e.deltaX)) {
          track.scrollLeft += e.deltaY;
          e.preventDefault();
        }
      }, { passive: false });

      let downX = 0;
      let startScroll = 0;
      let dragging = false;
      let moved = false;
      track.addEventListener('pointerdown', (e) => {
        downX = e.clientX;
        startScroll = track.scrollLeft;
        dragging = true;
        moved = false;
      });
      window.addEventListener('pointermove', (e) => {
        if (!dragging) return;
        const dx = e.clientX - downX;
        if (!moved && Math.abs(dx) > 6) moved = true;
        if (moved) {
          track.scrollLeft = startScroll - dx;
          track.classList.add('dragging');
        }
      });
      window.addEventListener('pointerup', () => {
        dragging = false;
        track.classList.remove('dragging');
      });
      track.addEventListener('click', (e) => {
        if (moved) {
          e.stopPropagation();
          e.preventDefault();
          moved = false;
        }
      }, true);
    }

    /* ---------- Selection: edges, neighbors, package deps ---------- */
    function clearHighlight() {
      for (const el of document.querySelectorAll('[data-agent].sel, [data-agent].nb, [data-agent].dep')) {
        el.classList.remove('sel', 'nb', 'dep');
      }
      for (const c of document.querySelectorAll('.conn.lit')) c.classList.remove('lit');
    }

    function highlightSelection(id) {
      clearHighlight();
      if (!id) return;
      const nb = new Set();
      const dep = new Set();
      for (const e of graph.edges) {
        if (e.kind === 'workflow') {
          if (e.source === id) nb.add(e.target);
          if (e.target === id) nb.add(e.source);
        } else {
          if (e.source === id) dep.add(e.target);
          if (e.target === id) dep.add(e.source);
        }
      }
      for (const el of document.querySelectorAll('[data-agent]')) {
        const aid = el.dataset.agent;
        if (aid === id) el.classList.add('sel');
        else if (nb.has(aid)) el.classList.add('nb');
        else if (dep.has(aid)) el.classList.add('dep');
      }
      const track = document.querySelector('.stage-path.active .stage-track');
      if (track) {
        const cell = track.querySelector('[data-agent="' + CSS.escape(id) + '"]');
        if (cell) {
          const prev = cell.previousElementSibling;
          const nextEl = cell.nextElementSibling;
          if (prev && prev.classList.contains('conn')) prev.classList.add('lit');
          if (nextEl && nextEl.classList.contains('conn')) nextEl.classList.add('lit');
        }
      }
    }

    function workflowsFor(id) {
      const set = new Set();
      for (const e of graph.edges) {
        if (e.kind === 'workflow' && (e.source === id || e.target === id)) set.add(e.label);
      }
      return Array.from(set).sort();
    }

    const panel = document.getElementById('panel');
    const scrim = document.getElementById('scrim');
    const panelContent = document.getElementById('panel-content');
    let panelOpen = false;

    function openPanel(id) {
      const n = nodesById[id];
      if (!n) return;
      selectedAgent = id;
      const wfs = workflowsFor(id);
      const wfUp = [], wfDown = [], depOut = [], depIn = [];
      for (const e of graph.edges) {
        if (e.kind === 'workflow') {
          if (e.source === id) wfDown.push(e);
          if (e.target === id) wfUp.push(e);
        } else {
          if (e.source === id) depOut.push(e);
          if (e.target === id) depIn.push(e);
        }
      }
      let html = '';
      html += '<div class="p-id">' + escape(n.id) + '</div>';
      html += '<h3>' + escape(n.name) + '</h3>';
      html += '<div class="badge' + (n.contract_status === 'stub' ? ' stub' : '') + '"><i></i>' + escape(n.contract_status) + '</div>';
      html += '<dl>';
      html += '<dt>Stage</dt><dd>' + escape(STAGE_NAMES[n.stage] || n.stage) + '</dd>';
      html += '<dt>Version</dt><dd>' + escape(n.version) + '</dd>';
      html += '<dt>Contract</dt><dd>' + (n.has_contract ? 'Yes' : 'No') + '</dd>';
      html += '<dt>Source</dt><dd><code>' + escape(n.source_path) + '</code></dd>';
      html += '</dl>';

      html += '<div class="p-label">Workflows</div>';
      if (wfs.length) {
        html += '<div class="mini-pills">';
        for (const w of wfs) {
          html += '<button type="button" class="mini-pill" data-wf-jump="' + escape(w) + '">' + escape(w) + '</button>';
        }
        html += '</div>';
      } else {
        html += '<p class="p-dim">Not part of a built-in workflow.</p>';
      }

      html += '<div class="p-label">Pipeline connections</div>';
      if (wfUp.length || wfDown.length) {
        html += '<ul class="conn-list">';
        for (const e of wfUp) {
          html += '<li><span class="dir">&larr;</span> <button type="button" data-jump="' + escape(e.source) + '">' + escape(e.source) + '</button> <span class="c-kind">' + escape(e.label) + '</span></li>';
        }
        for (const e of wfDown) {
          html += '<li><span class="dir">&rarr;</span> <button type="button" data-jump="' + escape(e.target) + '">' + escape(e.target) + '</button> <span class="c-kind">' + escape(e.label) + '</span></li>';
        }
        html += '</ul>';
      } else {
        html += '<p class="p-dim">No pipeline edges.</p>';
      }

      html += '<div class="p-label">Depends on</div>';
      if (depOut.length) {
        for (const e of depOut) {
          const t = nodesById[e.target];
          html += '<div class="dep-row"><button type="button" class="dep-pill" data-jump="' + escape(e.target) + '"><span class="dep-arrow">&#8674;</span> ' + escape(e.target) + (t ? ' · ' + escape(t.name) : '') + '</button><span class="dep-label">' + escape(e.label) + '</span></div>';
        }
      } else {
        html += '<p class="p-dim">No package dependencies.</p>';
      }

      html += '<div class="p-label">Required by</div>';
      if (depIn.length) {
        for (const e of depIn) {
          const s = nodesById[e.source];
          html += '<div class="dep-row"><button type="button" class="dep-pill" data-jump="' + escape(e.source) + '"><span class="dep-arrow">&#8672;</span> ' + escape(e.source) + (s ? ' · ' + escape(s.name) : '') + '</button><span class="dep-label">' + escape(e.label) + '</span></div>';
        }
      } else {
        html += '<p class="p-dim">Nothing depends on this package.</p>';
      }

      panelContent.innerHTML = html;
      panel.classList.add('open');
      panel.setAttribute('aria-hidden', 'false');
      scrim.hidden = false;
      requestAnimationFrame(() => scrim.classList.add('show'));
      panelOpen = true;
      highlightSelection(id);
      document.getElementById('panel-close').focus({ preventScroll: true });
    }
    function closePanel() {
      if (!panelOpen) return;
      panel.classList.remove('open');
      panel.setAttribute('aria-hidden', 'true');
      scrim.classList.remove('show');
      panelOpen = false;
      selectedAgent = null;
      clearHighlight();
      setTimeout(() => { if (!panelOpen) scrim.hidden = true; }, 350);
    }
    document.getElementById('panel-close').addEventListener('click', closePanel);
    scrim.addEventListener('click', closePanel);
    document.addEventListener('keydown', (ev) => { if (ev.key === 'Escape') closePanel(); });

    for (const btn of document.querySelectorAll('[data-agent]')) {
      btn.addEventListener('click', (ev) => {
        ev.stopPropagation();
        openPanel(btn.dataset.agent);
      });
    }

    panelContent.addEventListener('click', (ev) => {
      const jump = ev.target.closest('[data-jump]');
      if (jump) { openPanel(jump.dataset.jump); return; }
      const wfJump = ev.target.closest('[data-wf-jump]');
      if (wfJump) {
        const label = wfJump.dataset.wfJump;
        closePanel();
        setWorkflow(label);
        const stage = document.getElementById('stage');
        if (stage) stage.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth' });
        if (stageCard && !reduceMotion) {
          stageCard.classList.add('flash');
          setTimeout(() => stageCard.classList.remove('flash'), 1400);
        }
      }
    });

    /* ---------- Quiet filters ---------- */
    const searchEl = document.getElementById('search');
    const stageEl = document.getElementById('stage-filter');
    const statusEl = document.getElementById('status-filter');
    for (const tile of document.querySelectorAll('.tile')) {
      const o = document.createElement('option');
      o.value = tile.dataset.stage;
      o.textContent = tile.querySelector('.tile-stage').textContent;
      stageEl.appendChild(o);
    }
    function applyFilters() {
      const q = searchEl.value.trim().toLowerCase();
      const st = stageEl.value;
      const ss = statusEl.value;
      const filtering = q !== '' || st !== 'all' || ss !== 'all';
      for (const tile of document.querySelectorAll('.tile')) {
        const rows = tile.querySelectorAll('.agent-row');
        let matches = 0;
        for (const row of rows) {
          const n = nodesById[row.dataset.agent];
          let show = true;
          if (st !== 'all' && n.stage !== st) show = false;
          if (ss !== 'all' && n.contract_status !== ss) show = false;
          if (q && n.id.toLowerCase().indexOf(q) === -1 && n.name.toLowerCase().indexOf(q) === -1) show = false;
          row.parentElement.style.display = show ? '' : 'none';
          if (show) matches++;
        }
        tile.style.display = filtering && matches === 0 ? 'none' : '';
        const head = tile.querySelector('.tile-head');
        if (filtering && matches > 0) {
          tile.classList.add('open');
          head.setAttribute('aria-expanded', 'true');
        }
        const note = tile.querySelector('.tile-match');
        if (note) note.textContent = filtering ? matches + ' of ' + rows.length : '';
      }
    }
    searchEl.addEventListener('input', applyFilters);
    stageEl.addEventListener('change', applyFilters);
    statusEl.addEventListener('change', applyFilters);

    /* ---------- Init ---------- */
    applyPathHighlight();
    const firstPath = document.querySelector('.stage-path.active');
    if (firstPath) {
      if (reduceMotion) {
        firstPath.classList.add('in');
      } else {
        requestAnimationFrame(() => requestAnimationFrame(() => firstPath.classList.add('in')));
      }
    }
  </script>
</body>
</html>
`;
}

function main(): void {
  const repo = repoRoot();
  const graphPath = join(repo, GRAPH_PATH);
  if (!existsSync(graphPath)) {
    console.error(`${GRAPH_PATH} missing. Run \`pnpm gen:manifest\` first.`);
    process.exit(1);
  }
  const graph = JSON.parse(readFileSync(graphPath, 'utf8')) as AgentGraph;
  const html = renderAgentMapHtml(graph);
  const out = join(repo, MAP_HTML_PATH);
  writeFileSync(out, html);
  console.log(`Wrote ${MAP_HTML_PATH} (${graph.total_nodes} agents).`);
}

const isDirect =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirect) {
  main();
}
